### ISSUE TITLE
Getting error fromn Gtk3 gem

### ISSUE THREAD

**Issue by ghost** [ruby-gnome/ruby-gnome#1097]
Here's the error:

```text
/home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/armv7l-linux/2.4.0/gtk3-3.1.8/gtk3.so: undefined symbol: rbgobj_gc_mark_instance - /home/pi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/armv7l-linux/2.4.0/gtk3-3.1.8/gtk3.so (LoadError)
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /home/pi/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from gtk.rb:1:in `<main>' `
```

Here's the code:

```ruby
require 'gtk3'

class RubyApp < Gtk::Window

def initialize
    super

    set_title "Center"
    signal_connect "destroy" do 
        Gtk.main_quit 
    end

    set_default_size 300, 200

    set_window_position Gtk::Window::Position::CENTER
    
    show
end
end

Gtk.init
window = RubyApp.new
Gtk.main
```

I have no idea why such a simple program isn't working, and the error messages aren't helping. System is RPi3 Model B.

**Comment by kou** [comment]
Please show output of them:

```console
% ruby -d -e 'require "glib2"; puts $LOADED_FEATURES'
% ruby -d -e 'require "gtk3"; puts $LOADED_FEATURES'
% ruby -e 'p Gem::VERSION'
```
