### ISSUE TITLE
Gdk4 and Gdk::Atom

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome/ruby-gnome#1128]
@kou,

in Gdk4, it seems that the `Gdk::Atom` class is not automaticaly created, instead of that, all the related function for the atoms are functions of the Gdk4 module:

```ruby
puts Gdk.methods.grep(/atom/)
x11_atom_to_xatom
x11_atom_to_xatom_for_display                                                                                                                  
x11_get_xatom_by_name                                                                                                                          
x11_get_xatom_by_name_for_display                                                                                                              
x11_get_xatom_name     
x11_get_xatom_name_for_display                                                                                                                 
x11_xatom_to_atom 
x11_xatom_to_atom_for_display                                                                                                                 atom_intern                          
atom_intern_static_string   
atom_name 
``` 

Should we keep the same organization as before with a `Gdk::Atom`, if so should I try to map all the functions with a pattern (*atom*) with the loader.rb and create/fill the `Gdk::Atom` class there or should I
generate everything in the **gdk4/lib/gdk4/atom.rb** ?

**Comment by kou** [comment]
It seems that `Gdk::Atom.intern` and `Gdk::Atom#name` work well.
We need more works just only for X11 relation atom functions.

I'll check it later.

**Comment by cedlemo** [comment]
Well, I still have this with the jhbuilder environment that I just updated to be sure:

```bash
./gdk4_test.sh                                                                                                                                               Projets/Ruby
Traceback (most recent call last):
        15: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/test/run-test.rb:56:in `<main>'
        14: from /home/cedlemo/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        13: from /home/cedlemo/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        12: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4.rb:33:in `<top (required)>'
        11: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4.rb:41:in `<module:Gdk>'
        10: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/loader.rb:21:in `load'
         9: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gobject-introspection/lib/gobject-introspection/loader.rb:45:in `load'
         8: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/loader.rb:41:in `post_load'
         7: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/loader.rb:45:in `require_libraries'
         6: from /home/cedlemo/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from /home/cedlemo/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         4: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/atom.rb:17:in `<top (required)>'
         3: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/atom.rb:18:in `<module:Gdk>'
         2: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/atom.rb:19:in `<class:Atom>'
         1: from /home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/atom.rb:20:in `singleton class'
/home/cedlemo/Projets/Ruby/ruby-gnome2/gdk4/lib/gdk4/atom.rb:20:in `alias_method': undefined method `intern' for class `#<Class:Gdk::Atom>' (NameError)
Did you mean?  Integer
```

My script that is in `ruby-gnome2/../` :

```bash
#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/ruby-gnome2"

export GI_TYPELIB_PATH="/home/$USER/jhbuild/install/lib/girepository-1.0"
export LD_LIBRARY_PATH="/home/$USER/jhbuild/install/lib"

if [ $# -eq 0 ]
  then
   $DIR/gdk4/test/run-test.rb
  else
   $DIR/gdk4/test/run-test.rb -t $1
fi
```

**Comment by kou** [comment]
Ah, it seems that `gdk_atom_intern()` was dropped since GTK+ 3.93.0: https://git.gnome.org/browse/gtk+/commit/gdk/gdkproperty.h?id=54a62731916bbf724b53f0c9fc2bd1addb85802f

We should remove `gdk4/lib/gdk4/atom.rb` and implement `g_intern_string()`.

**Comment by cedlemo** [comment]
@kou,

yes that is why I added the roadmap of Gdk4 and gtk4 in the gdk4 README :
 
* https://wiki.gnome.org/Projects/GTK+/gdk4
* https://wiki.gnome.org/Projects/GTK+/Roadmap/GTK4

**Comment by kou** [comment]
We don't provide `Gdk::Atom`.
