### ISSUE TITLE
How to implement GInterface.

### ISSUE THREAD

**Issue by ghost** [ruby-gnome/ruby-gnome#1165]
This is as far as I got, is this allowed in ruby-gtk3 3.2.1+?
```
# irb
class SxStyle < GLib::Instantiatable
include Gtk::StyleProvider
end

#=> TypeError: superclass mismatch for class SxStyle
```

```
#!/usr/bin/ruby
require "gtk3"

#full script

class SxStyle < GLib::Instantiatable
include Gtk::StyleProvider
	def initialize()
		@style = {}
	end
	def set_style_property(path, state, value)
		if @style[path] != nil
			@style[path][state] = value
		else
			@style[path] = { state => value }
		end
	end
	alias []= set_style_property
	def get_style_property(path, state, pspec)
		return @style.dig(path, state)
	end
end

$wind = Gtk::Window.new
$text = Gtk::Label.new

$style = SxStyle.new
$rgba = Gtk::RGBA.new
$rgba.parse("#FFFFFF")
$style[$text.widget_path, Gtk::StateFlag::NORMAL] = $rgba

$text.style_context.add_provider(800, $style)
$wind.add($text)
$wind.show_all

Gtk.main

#./test.rb:26:in `new': abstract class (TypeError)
#	from ./test.rb:26:in `<main>'

```

**Comment by kou** [comment]
It's not implemented yet.
See also #985.

**Comment by kou** [comment]
Implemented.
