### ISSUE TITLE
gtk-demo error: Combo Boxes

### ISSUE THREAD

**Issue by kojix2** [ruby-gnome/ruby-gnome#1176]
gtk-demo error report
```bash
/ruby-gnome2/gtk3/sample/gtk-demo$ ruby main.rb
```
When I changeed the 3rd editable entry's value, it crashed.
This is the error message.
```bash
gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke': <Gtk::Entry#set_attributes>: the 0th argument must not nil: <attrs>
	 from gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
	 from /ruby-gnome2/gtk3/sample/gtk-demo/combobox.rb:278:in `set_background'
	 from /ruby-gnome2/gtk3/sample/gtk-demo/combobox.rb:265:in `block in initialize'
	 from gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `invoke'
	 from gem/ruby/2.5.0/gems/gobject-introspection-3.2.6/lib/gobject-introspection/loader.rb:585:in `block in define_method'
	 from main.rb:518:in `<main>'
main.rb: [BUG] Segmentation fault at 0x0000000000000030
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
```

<Gtk::Entry#set_attributes> pass nil here.
https://github.com/ruby-gnome2/ruby-gnome2/blob/01b94504cf1b3c773d382c7a39ae551e494017a2/gtk3/sample/gtk-demo/combobox.rb#L278

The following short script gives me the same error.
```ruby
require 'gtk3'
e = Gtk::Entry.new
e.set_attributes nil
```
```console
<Gtk::Entry#set_attributes>: the 0th argument must not nil: <attrs> (ArgumentError)
```

system:
- Ubuntu 16.04
- ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
- libgtk-3-0 3.18.9-1ubuntu3.3
- ruby gtk3 (3.2.6)

**Comment by kou** [comment]
It's a GTK+ problm. We should send the following patch to the GTK+ developers:

```diff
diff --git a/gtk/gtkentry.c b/gtk/gtkentry.c
index 9a4a0f75de..8b4ef54547 100644
--- a/gtk/gtkentry.c
+++ b/gtk/gtkentry.c
@@ -9418,7 +9418,7 @@ gtk_entry_get_input_hints (GtkEntry *entry)
 /**
  * gtk_entry_set_attributes:
  * @entry: a #GtkEntry
- * @attrs: a #PangoAttrList
+ * @attrs: (nullable): a #PangoAttrList
  *
  * Sets a #PangoAttrList; the attributes in the list are applied to the
  * entry text.
```

Can you send it to https://gitlab.gnome.org/GNOME/gtk ?

**Comment by kojix2** [comment]
Thank you very much. I would like to send this patch to Gnome. Oh .. Send patch to GTK+ developers ... It sounds awesome. I don't know what to do.  But I will try it.
