### ISSUE TITLE
Gio::Icon.hash: wrong number of arguments (0 for 1) (ArgumentError)

### ISSUE THREAD

**Issue by morpheus747** [ruby-gnome/ruby-gnome#1293]
Hi, i'm trying to compile the examples from GTK3/samples to windows .exe with ocra but i fail again and again and again with this error.

```text
C:\Users\Erik\Desktop\proyectos\ruby\pruebas>ocra t1.rb
=== Loading script to check dependencies
=== Attempting to trigger autoload of Gem::SpecFetcher
=== Attempting to trigger autoload of Gem::SourceList
=== Attempting to trigger autoload of Gem::ConfigFile
=== Attempting to trigger autoload of Gem::Licenses
=== Attempting to trigger autoload of Gem::Installer
=== Attempting to trigger autoload of Gem::DependencyList
=== Attempting to trigger autoload of Module::IPAddr
=== Attempting to trigger autoload of RubyInstaller::Runtime::Components::Base
=== WARNING: RubyInstaller::Runtime::Components::Base was defined autoloadable, but caused NameError
=== Attempting to trigger autoload of RubyInstaller::Runtime::Ridk
=== Attempting to trigger autoload of RubyInstaller::Runtime::PACKAGE_VERSION
=== Attempting to trigger autoload of RubyInstaller::Runtime::ComponentsInstaller
Traceback (most recent call last):
        8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:1203:in `block in <top (required)>'
        7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:723:in `build_exe'
        6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:464:in `attempt_load_autoload'
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:464:in `loop'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:470:in `block in attempt_load_autoload'
        3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:470:in `each'
        2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ocra-1.3.10/bin/ocra:471:in `block (2 levels) in attempt_load_autoload'
        1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.7/lib/gobject-introspection/loader.rb:99:in `block in define_singleton_method'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gobject-introspection-3.3.7/lib/gobject-introspection/loader.rb:606:in `invoke': Gio::Icon.hash: wrong number of arguments (0 for 1) (ArgumentError)
```

i search on internet but in don't found any information usefull to solve the problem, (except one japanese site that for some reason use QT to set the icon)
and i realy don't understand the error.
I think the app icon is not set i try to set with ocra --icon and set my .ico file to try to solve the problem.
Then i try to set the Gio icon in my app but i don't know how (im noob) i search here and can't found any information about how to set the application window icon.

Can you help me please.

**Comment by kou** [comment]
It's a bug of gio2 gem.
We'll fix it in the next release.

Workaround:

```console
$ cat workaround-gio2.rb
require "gio2"
if Gio::Icon.method(:hash).owner == Gio::Icon
  Gio::Icon.singleton_class.remove_method(:hash)
end
$ ruby -r ./workaround-gio2 -S ocra t1.rb
```

**Comment by morpheus747** [comment]
is not work but i use
`require "gio2"
Gio::Icon.singleton_class.remove_method(:hash)`

Note the ./   from the workaround file is required in windows for the command to work.

Only that and "compile" now after that just open cmd, excecute the .exe and die with
6: The specified module could not be found.   - C:/Users/morpheus747/AppData/Local/Temp/ocr3D84.tmp/lib/ruby/gems/2.5.0/gems/glib2-3.3.7/lib/glib2.so (LoadError)

That is another animal. will search for that.
Thanks !

**Comment by kou** [comment]
Fix:

```ruby
if Gio::Icon.method(:hash).owner == Gio::Icon.singleton_class
```
