### ISSUE TITLE
TODO: [attributes] out free GIArgument(array)[everything]

### ISSUE THREAD

**Issue by aycabta** [ruby-gnome/ruby-gnome#1356]
Simple example:

```ruby
require "vte3"
terminal = Vte::Terminal.new
terminal.get_text_range(0, 0, 1, 1)
```

Result:

```
$ ruby test.rb
Traceback (most recent call last):
        3: from test.rb:3:in `<main>'
        2: from /home/aycabta/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:514:in `block in define_method'
        1: from /home/aycabta/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:600:in `invoke'
/home/aycabta/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.1/lib/gobject-introspection/loader.rb:600:in `invoke': TODO: [attributes] out free GIArgument(array)[everything] (NotImplementedError)
```

**Comment by kou** [comment]
Thanks for your report.
I've implemented this.
