### ISSUE TITLE
gobject-introspection is weird: confusing error messages: "null" and similar messages should ideally be improved on, from a ruby point of view, if possible

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1419]
gobject-introspection is weird: confusing error messages

Hey ruby-gtk devs and everyone else,

I am trying to compile standalone examples for both ruby-gtk2
and ruby-gtk3. So far so good. I am also slowly porting my
old ruby-gtk2 to ruby-gtk3; that works. (And hopefully 
libui may one day be an additional UI choice, but I digress)

Anyway.

I am working on an example for RadioMenuItem.

When running it I get this:

```text
ruby radio_menu_item_example.rb
 
Traceback (most recent call last):
        3: from radio_menu_item_example.rb:15:in `<main>'
        2: from radio_menu_item_example.rb:15:in `new'
        1: from /root/.gem/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:337:in `block in load_methods_constructor'
/root/.gem/gems/gobject-introspection-3.4.3/lib/gobject-introspection/loader.rb:334:in `block in load_methods_constructor': wrong arguments: Gtk::RadioMenuItem#initialize("RadioMenuItem 1"): available signatures: (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem)))): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem))): (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem))), label: utf8): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem)), label: (may be null) utf8): (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem))), label: utf8): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem)), label: (may be null) utf8) (ArgumentError)
```

The code is:

----
    require 'gtk3'

    window = Gtk::Window.new
    box = Gtk::Box.new(:horizontal)
    menuitem = Gtk::MenuItem.new(label: '_RadioMenuItem', use_underline: true)
    menubar = Gtk::MenuBar.new
    menubar.append(menuitem)

    menu = Gtk::Menu.new
    menuitem.set_submenu(menu)
    radiomenuitem1 = Gtk::RadioMenuItem.new(label = 'RadioMenuItem 1')
    radiomenuitem1.set_active(true)
    menu.append(radiomenuitem1)

    radiomenuitem2 = Gtk::RadioMenuItem.new(label = 'RadioMenuItem 2', group = radiomenuitem1)
    menu.append(radiomenuitem2)

    box.add(menu)
    window.add(box)
    window.show_all
    window.move(0, 0)
    Gtk.main

----

I am sure I will eventually find out the error, but my issue
is NOT about the code above. My issue is with the error
message from gobject-introspection.

Let me focus on it again, to make this more clear:

    loader.rb:334:in `block in load_methods_constructor': wrong arguments: Gtk::RadioMenuItem#initialize("RadioMenuItem 1"): available signatures: (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem)))): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem))): (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem))), label: utf8): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem)), label: (may be null) utf8): (group: (may be null) gslist(interface(Gtk::RadioMenuItem(GtkRadioMenuItem))), label: utf8): (group: (may be null) interface(Gtk::RadioMenuItem(GtkRadioMenuItem)), label: (may be null) utf8) (ArgumentError)

This is what I get. First, the loader.rb is a bit useless,
but even more importantly, on the commandline I have
output like this:

    (group: (may be null) interface

I don't know how this originates; perhaps from the C side.

But either way, the error message does not tell me anything.

Compare it to this instead, which I just fixed:

    radio_menu_item_example.rb:9:in `new': 'Gtk::MenuItem#initialize(label, use_underline=false)' style has been deprecated. Use 'Gtk::MenuItem#initialize(:label => label, :use_underline => use_underline)' style.

This error message is MUCH more useful, because it tells
me WHERE the problem is, and WHAT the problem is. So
when using e. g. use_underline: the error went away.

But the other error message, the "group: (may be null"
does not tell me anything. I don't get any lines either.

Right now this is a bit useless to me.

I assume that this is perhaps the way how gobject-introspection
works and perhaps it is not trivial to change. But if in the
future someone may want to have a look, it would be SUPER
helpful if the error messages could be more explicit, like
the other messages too. The "group may be null interface"
really does not tell me anything. I don't even know what
null means in ruby, so I assume this originates from the
C/glib side perhaps? I am still not an expert in gtk, I
am just trying to tweak ruby until it works. :D

Anyway please do feel free to close this issue at any
moment in time!

**Comment by rubyFeedback** [comment]
Ok the fix was simple:

    first  = Gtk::RadioMenuItem.new(nil,   'First')

I just had to provide nil as the first argument. But I figured this out not from the error
message, but from a .rb file in the demo example of gtk3. :)
