### ISSUE TITLE
weird mkmf-gnome2 installation fail message

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1420]
Hi there,

I have recently switched to another distribution and am compiling and installing
lots of things.

The following fails:

"gem install gtk2"

Building native extensions. This could take a while...
ERROR:  Error installing gtk2:
        ERROR: Failed to build gem native extension.

    current directory: /root/.gem/gems/gtk2-3.4.3/ext/gtk2
/usr/bin/ruby -I /usr/lib/ruby/site_ruby/2.7.0 -r ./siteconf20210111-23170-x44isk.rb extconf.rb
/usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- mkmf-gnome2 (LoadError)
        from /usr/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
        from extconf.rb:40:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /root/.gem/gems/gtk2-3.4.3 for inspection.
Results logged to /root/.gem/extensions/x86_64-linux/2.7.0-static/gtk2-3.4.3/gem_make.out

---

I think I'll get it to work eventually, but what was confusing me was this one:

mkmf-gnome2 

I have not found such a gem. Perhaps this is very old? In this case I think it
may be best to remove all references to mkmf-gnome2, because I thought I'd
need that gem (not sure how I ended up there anyway, my system is a bit 
of a mess right now; always takes me a while before I set things up properly).

Thanks!

**Comment by pterjan** [comment]
mkmf-gnome2 is not a separate gem, it is part of glib2
