### ISSUE TITLE
Error: undefined method `new_for_font_type' for free type font face

### ISSUE THREAD

**Issue by goseinthemachine** [ruby-gnome/ruby-gnome#1429]
I have come across an issue with `Pango::CairoLoader` on macOS Big Sur v11.4 with ruby version 2.7.3 and up. I want to post an issue as I haven't seen anyone else come across this issue. Also want to make sure it is not a problem with the environment I am working in.

The issue I am having is that when the `post_load` method sets the `font_map` variable with a `Pango::CairoFontMap` object without the method `new_for_font_type`. As a result loading the `font_map` fails for the `font_type` `:ft`.

I wrapped lines 31-34 in a begin and rescue block to print the error and outputted the `font_type` before it was loaded to verify which font it was. This is the output:

```
quartz # Loading the first font_type font_map works but sets font_map to Pango::CairoFontMap object without new_for_font_type method
ft # Loading the freetype font_map fails. This is because the font_map set for the quartz font_type is missing the new_for_font_type method
Traceback (most recent call last):
	13: from /Users/camerongose/.asdf/installs/ruby/2.7.3/bin/squib:23:in `<main>'
	12: from /Users/camerongose/.asdf/installs/ruby/2.7.3/bin/squib:23:in `load'
	11: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/squib-0.16.0/bin/squib:2:in `<top (required)>'
	10: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 9: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 8: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/squib-0.16.0/lib/squib.rb:3:in `<top (required)>'
	 7: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 6: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
	 5: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/pango-3.4.5/lib/pango.rb:27:in `<top (required)>'
	 4: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/pango-3.4.5/lib/pango.rb:35:in `<module:Pango>'
	 3: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/gobject-introspection-3.4.5/lib/gobject-introspection/loader.rb:45:in `load'
	 2: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/pango-3.4.5/lib/pango/cairo-loader.rb:30:in `post_load'
	 1: from /Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/pango-3.4.5/lib/pango/cairo-loader.rb:30:in `each'
/Users/camerongose/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/pango-3.4.5/lib/pango/cairo-loader.rb:33:in `block in post_load': undefined method `new_for_font_type' for #<Pango::CairoCoreTextFontMap:0x7fdf5f067368 ptr=0x7fdf587b2e50> (NoMethodError)
```

I have linked the code that appears to be problematic. 
https://github.com/ruby-gnome/ruby-gnome/blob/686869767f5f18a4c6b3cb9c323e4afebbd270f6/pango/lib/pango/cairo-loader.rb#L24-L36

I am willing to help just need to know what kind of direction to go with this. Currently to get it working on my system I just have the problematic code wrapped in a rescue block so it silently fails. The library [Squib](https://github.com/andymeneely/squib/) that is using Pango appears to be working fine without the freetype font map loading.

**Comment by goseinthemachine** [comment]
One potential solution is to change line 31 variable name to `current_font_map` so that it is not changing the value of the variable assigned on line 25. Then update the variable used in lines 32-33.
```ruby
 def post_load(repository, namespace)
  font_map = @base_module.const_get("CairoFontMap")
  font_types = []
  font_types << :quartz if Cairo::FontFace.quartz_supported?
  font_types << :win32 if Cairo::Surface.quartz_supported?
  font_types << :ft if Cairo::FontFace.freetype_supported?
  font_types.each do |font_type|
      current_font_map = font_map.new_for_font_type(font_type)
      next if current_font_map.nil?
      @base_module.const_set(current_font_map.class.gtype.name.gsub(/\APango/, ""),
                             current_font_map.class)
  end
end
```

**Comment by kou** [comment]
Oh, sorry.
I've fixed an released a new version.
