### ISSUE TITLE
gtk2 module crahes with openssl moule: superclass mismatch for class Socket (TypeError)

### ISSUE THREAD

**Issue by dleidert** [ruby-gnome/ruby-gnome#1449]
Hi,

I know you have dropped development of the gtk2 module. However, there are a few programs out there still depending on it. We now became aware of a problem when loading the gtk2 module and the openssl module. The following script:

```
require 'gtk2'
include Gtk
require 'openssl'
```

crashes with

```
Traceback (most recent call last):
	14: from test.rb:3:in `<main>'
	13: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	12: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	11: from /usr/lib/ruby/2.7.0/openssl.rb:21:in `<top (required)>'
	10: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 9: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 8: from /usr/lib/ruby/2.7.0/openssl/ssl.rb:15:in `<top (required)>'
	 7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 6: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 5: from /usr/lib/ruby/2.7.0/ipaddr.rb:19:in `<top (required)>'
	 4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
	 2: from /usr/lib/ruby/2.7.0/socket.rb:3:in `<top (required)>'
	 1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': superclass mismatch for class Socket (TypeError)
```

Do you havy any idea how to fix that?

**Comment by kou** [comment]
How about removing `include Gtk`?

**Comment by dleidert** [comment]
I don't think that this is an option. The program failing is origami-pdf, which uses the gtk2 module and does essentially the same as in the example (the smallest case to reproduce the issue). If I remove the include statement, I get various NameErrors  and I suppose the include statement resolves them.

**Comment by kou** [comment]
Was the error by `require 'openssl'` is solved by removing `include Gtk`?

**Comment by dleidert** [comment]
Yes, just requiring 'gtk2' together with 'openssl' doesn't throw the TypeError. The include statement is vital to provoke the error.

**Comment by kou** [comment]
Then, the following will work:

```ruby
require 'gtk2'
require 'openssl'
include Gtk
```

**Comment by dleidert** [comment]
That seems to be a workaround indeed.

**Comment by kou** [comment]
Can we close this?

**Comment by dleidert** [comment]
Yes, I think so.
