### ISSUE TITLE
3.5.1 gio2 some tests fail on 32bit

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1462]
On 32 bit arch (e.g. i686 and armv7hl) some tests fail on gio2 3.5.1 (one ommision is Fedora specific)

```
.......E
===============================================================================
Error: test_skip(TestRubyInputStream):
  GLib::Error: bignum too big to convert into `unsigned long'
    /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `initialize'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `new'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `virtual_do_read_fn'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `read'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:63:in `read_raw_compatible'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:46:in `read'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:39:in `test_skip'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:871:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:274:in `block (2 levels) in create_fixtures_runner'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:22:in `block in setup'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:20:in `setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:284:in `run_fixture_callback'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:272:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:257:in `run_fixture'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:292:in `run_setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:564:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:25:in `start'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:458:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:514:in `change_work_directory'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:457:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:66:in `run'  
  /usr/share/gems/gems/glib2-3.5.1/lib/glib2/test/run-test.rb:70:in `run_test'  
  test/run-test.rb:21:in `<main>'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `read'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:63:in `read_raw_compatible'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:46:in `read'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:39:in `test_skip'
     36: 
     37:   def test_skip
     38:     assert_equal(1, @stream.skip(1))
  => 39:     assert_equal("ell", @stream.read(3))
     40:   end
     41: 
     42:   def test_tell
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:22:in `block in setup'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:20:in `setup'
===============================================================================
..E
===============================================================================
Error: test_with_size(TestRubyInputStream::#read):
  GLib::Error: bignum too big to convert into `unsigned long'
    /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `initialize'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `new'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `virtual_do_read_fn'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `read'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:63:in `read_raw_compatible'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:46:in `read'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:28:in `test_with_size'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:871:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:274:in `block (2 levels) in create_fixtures_runner'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:22:in `block in setup'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:20:in `setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:284:in `run_fixture_callback'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:272:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:257:in `run_fixture'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:292:in `run_setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:564:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:25:in `start'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:458:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:514:in `change_work_directory'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:457:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:66:in `run'  
  /usr/share/gems/gems/glib2-3.5.1/lib/glib2/test/run-test.rb:70:in `run_test'  
  test/run-test.rb:21:in `<main>'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `read'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:63:in `read_raw_compatible'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:46:in `read'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:28:in `test_with_size'
     25: 
     26:   sub_test_case("#read") do
     27:     def test_with_size
  => 28:       assert_equal("H", @stream.read(1))
     29:       assert_equal("ell", @stream.read(3))
     30:     end
     31: 
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:22:in `block in setup'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-input-stream.rb:20:in `setup'
===============================================================================
.....E
===============================================================================
Error: test_splice(TestRubyOutputStream):
  GLib::Error: bignum too big to convert into `unsigned long'
    /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `initialize'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `new'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/ruby-input-stream.rb:40:in `virtual_do_read_fn'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'  
  /usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `splice'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:33:in `block in test_splice'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:32:in `test_splice'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:871:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:566:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:274:in `block (2 levels) in create_fixtures_runner'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:22:in `block in setup'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/output-stream.rb:25:in `open'  
  /builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:20:in `setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:284:in `run_fixture_callback'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:272:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:276:in `block in create_fixtures_runner'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:257:in `run_fixture'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/fixture.rb:292:in `run_setup'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:564:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testcase.rb:563:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:124:in `run_test'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/testsuite.rb:53:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:67:in `run_suite'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:45:in `block (2 levels) in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:102:in `with_listener'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:41:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `catch'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnermediator.rb:39:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:40:in `start_mediator'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunner.rb:25:in `start'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/ui/testrunnerutilities.rb:24:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:458:in `block in run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:514:in `change_work_directory'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:457:in `run'  
  /usr/share/gems/gems/test-unit-3.5.3/lib/test/unit/autorunner.rb:66:in `run'  
  /usr/share/gems/gems/glib2-3.5.1/lib/glib2/test/run-test.rb:70:in `run_test'  
  test/run-test.rb:21:in `<main>'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/usr/share/gems/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `splice'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:33:in `block in test_splice'
     30: 
     31:   def test_splice
     32:     Gio::RubyInputStream.open(StringIO.new("Hi")) do |input_stream|
  => 33:       assert_equal(2, @stream.splice(input_stream, :none))
     34:     end
     35:     assert_equal("Hillo World", @base_stream.string)
     36:   end
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/input-stream.rb:25:in `open'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:32:in `test_splice'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:22:in `block in setup'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2/lib/gio2/output-stream.rb:25:in `open'
/builddir/build/BUILD/gio2-3.5.1/usr/share/gems/gems/gio2-3.5.1/test/test-ruby-output-stream.rb:20:in `setup'
===============================================================================
........................
Finished in 0.183671514 seconds.
-------------------------------------------------------------------------------
91 tests, 115 assertions, 0 failures, 3 errors, 0 pendings, 1 omissions, 0 notifications
96.6667% passed
-------------------------------------------------------------------------------```

**Comment by kou** [comment]
Could you try https://github.com/ruby-gnome/ruby-gnome/commit/6368d5f570b8d895bd6f6b268e0f1e15fb602026 ?

**Comment by mtasaka** [comment]
Confirmed fixed, thank you!

**Comment by kou** [comment]
Good to hear that!
