### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by mikwee** [ruby-gnome/ruby-gnome#1473]
Tried to install the GTK3 Ruby bindings on Windows 10, and got this error:
```
current directory: C:/Users/mikwee/scoop/apps/ruby/current/gems/gems/glib2-3.5.1/ext/glib2
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r ./siteconf20220429-1768-pcuqys.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... no
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... no
checking for gobject-2.0 version (>= 2.12.0)... no
installing 'mingw-w64-ucrt-x86_64-glib2' native package... failed
Failed to run 'pacman.exe -S --noconfirm mingw-w64-ucrt-x86_64-glib2'.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Users/mikwee/scoop/apps/ruby/current/gems/extensions/x64-mingw-ucrt/3.1.0/glib2-3.5.1/mkmf.log

extconf failed, exit code 1

```

**Comment by mikwee** [comment]
Update;
Tried the Gemfile method too, ended with this error:
```
Fetching https://github.com/ruby-gnome/ruby-gnome.git
Updating files:  72% (1711/2358)
Updating files:  73% (1722/2358)
Updating files:  74% (1745/2358)
Updating files:  75% (1769/2358)
Updating files:  76% (1793/2358)
Updating files:  77% (1816/2358)
Updating files:  78% (1840/2358)
Updating files:  79% (1863/2358)
Updating files:  80% (1887/2358)
Updating files:  81% (1910/2358)
Updating files:  82% (1934/2358)
Updating files:  83% (1958/2358)
Updating files:  84% (1981/2358)
Updating files:  85% (2005/2358)
Updating files:  86% (2028/2358)
Updating files:  87% (2052/2358)
Updating files:  88% (2076/2358)
Updating files:  89% (2099/2358)
Updating files:  90% (2123/2358)
Updating files:  91% (2146/2358)
Updating files:  92% (2170/2358)
Updating files:  93% (2193/2358)
Updating files:  94% (2217/2358)
Updating files:  95% (2241/2358)
Updating files:  96% (2264/2358)
Updating files:  97% (2288/2358)
Updating files:  98% (2311/2358)
Updating files:  99% (2335/2358)
Updating files: 100% (2358/2358)
Updating files: 100% (2358/2358), done.
Resolving dependencies...Fetching gem metadata from https://rubygems.org/...
..
Using bundler 2.3.7
Using fiddle 1.1.0
Using pkg-config 1.4.7
Using native-package-installer 1.1.4
Fetching matrix 0.4.2
Installing matrix 0.4.2
Using glib2 3.5.2 from https://github.com/ruby-gnome/ruby-gnome.git (at master@22953e2)
Fetching red-colors 0.3.0
Installing red-colors 0.3.0
Fetching cairo 1.17.5
Installing cairo 1.17.5 with native extensions
warning: warning: Public keyring not found; have you run 'Public keyring not found; have you run 'pacman-key --initpacman-key --init'?
'?
error: error: mingw32mingw32: key ": key "5F944B027F7FE2091985AA2EFA11531AA0AA7F575F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
" is unknown
error: keyring is not writable
error: keyring is not writable
error: error: mingw64mingw64: key ": key "5F944B027F7FE2091985AA2EFA11531AA0AA7F575F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
" is unknown
error: error: keyring is not writable
keyring is not writable
error: error: ucrt64ucrt64: key ": key "5F944B027F7FE2091985AA2EFA11531AA0AA7F575F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
" is unknown
error: error: keyring is not writable
keyring is not writable
error: error: clang64clang64: key ": key "5F944B027F7FE2091985AA2EFA11531AA0AA7F575F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
" is unknown
error: keyring is not writable
error: keyring is not writable
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: error: keyring is not writable
msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: error: database 'database 'mingw32mingw32' is not valid (' is not valid (invalid or corrupted database (PGP signature)invalid or corrupted database (PGP signature))
)
error: error: database 'database 'mingw64mingw64' is not valid (' is not valid (invalid or corrupted database (PGP signature)invalid or corrupted database (PGP signature))
)
error: error: database 'database 'ucrt64ucrt64' is not valid (' is not valid (invalid or corrupted database (PGP signature)invalid or corrupted database (PGP signature))
)
error: error: database 'database 'clang64clang64' is not valid (' is not valid (invalid or corrupted database (PGP signature)invalid or corrupted database (PGP signature))
)
error: error: database 'database 'msysmsys' is not valid (' is not valid (invalid or corrupted database (PGP signature)invalid or corrupted database (PGP signature))
)
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Users/mikwee/scoop/apps/ruby/current/gems/bundler/gems/ruby-gnome-22953e2b6135/glib2/ext/glib2
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
./siteconf20220429-16592-g8msau.rb extconf.rb
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... no
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... no
checking for gobject-2.0 version (>= 2.12.0)... no
installing 'mingw-w64-ucrt-x86_64-glib2' native package... failed
Failed to run 'pacman.exe -S --noconfirm mingw-w64-ucrt-x86_64-glib2'.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
        --enable-debug-build
        --disable-debug-build
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Users/mikwee/scoop/apps/ruby/current/gems/bundler/gems/ruby-gnome-22953e2b6135/extensions/x64-mingw-ucrt/3.1.0/ruby-gnome-22953e2b6135-glib2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Users/mikwee/scoop/apps/ruby/current/gems/bundler/gems/ruby-gnome-22953e2b6135/glib2
for inspection.
Results logged to
C:/Users/mikwee/scoop/apps/ruby/current/gems/bundler/gems/ruby-gnome-22953e2b6135/extensions/x64-mingw-ucrt/3.1.0/ruby-gnome-22953e2b6135-glib2/gem_make.out

  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
build'
  C:/Ruby31-x64/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/source/path/installer.rb:34:in
`post_install'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/source/path.rb:244:in `generate_bin'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/source/git.rb:194:in `install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in
`install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing glib2 (3.5.2), and Bundler cannot continue.

In Gemfile:
  gtk3 was resolved to 3.5.2, which depends on
    atk was resolved to 3.5.2, which depends on
      glib2


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Users/mikwee/scoop/apps/ruby/current/gems/gems/cairo-1.17.5/ext/cairo
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r
./siteconf20220429-16592-7hirov.rb extconf.rb
checking for GCC... yes
checking for Homebrew... no
checking for cairo version (>= 1.2.0)... no
installing 'mingw-w64-ucrt-x86_64-cairo' native package... failed
Failed to run 'pacman.exe -S --noconfirm mingw-w64-ucrt-x86_64-cairo'.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
        --with-pkg-config
        --without-pkg-config
        --with-override-variables
        --without-override-variables

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/Users/mikwee/scoop/apps/ruby/current/gems/extensions/x64-mingw-ucrt/3.1.0/cairo-1.17.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/Users/mikwee/scoop/apps/ruby/current/gems/gems/cairo-1.17.5 for inspection.
Results logged to
C:/Users/mikwee/scoop/apps/ruby/current/gems/extensions/x64-mingw-ucrt/3.1.0/cairo-1.17.5/gem_make.out

  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
build'
  C:/Ruby31-x64/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:28:in `install'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in
`install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
  C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
C:/Ruby31-x64/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in
create_threads'

An error occurred while installing cairo (1.17.5), and Bundler cannot continue.

In Gemfile:
  gtk3 was resolved to 3.5.2, which depends on
    gdk3 was resolved to 3.5.2, which depends on
      pango was resolved to 3.5.2, which depends on
        cairo-gobject was resolved to 3.5.2, which depends on
          cairo
```

**Comment by kou** [comment]
Could you run `ridk exec pacman.exe -S --noconfirm mingw-w64-ucrt-x86_64-glib2` and show the output?

**Comment by mikwee** [comment]
Thanks for responding! Here's the output:
```
warning: Public keyring not found; have you run 'pacman-key --init'?
error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: ucrt64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: clang64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: msys: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown
error: keyring is not writable
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'ucrt64' is not valid (invalid or corrupted database (PGP signature)) 
error: database 'clang64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))  
````

**Comment by kojix2** [comment]
I think I saw the same error recently. I ended up reinstalling Ruby+DevKit with RubyInstaller.
I know this is not the answer you are looking for, but if you can reinstall Ruby and MinGW, it is worth a try.

**Comment by kou** [comment]
Could you run `ridk exec pacman-key --init` and then re-run `ridk exec pacman.exe -S --noconfirm mingw-w64-ucrt-x86_64-glib2` after it?

**Comment by mikwee** [comment]
I’ll try to do that, I am sick so it might take time.

**Comment by mikwee** [comment]
Oh golly, it seems like `pacman-key` isn't installed:
```
'pacman-key' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mikwee** [comment]
Update: Tried to install inside WSL and it works, probably because GTK isn't really meant for Windows.
