### ISSUE TITLE
Tool Palette demo doesn't run

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1475]
```
failed to run demo: ./toolpalette.rb
TypeError: (null) isn't supported
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `group'
/home/sjs/tmp/gtk-demo/toolpalette.rb:354:in `block in load_toggle_items'
/home/sjs/tmp/gtk-demo/toolpalette.rb:349:in `each'
/home/sjs/tmp/gtk-demo/toolpalette.rb:349:in `load_toggle_items'
/home/sjs/tmp/gtk-demo/toolpalette.rb:97:in `create_and_fill_the_toolpalette'
/home/sjs/tmp/gtk-demo/toolpalette.rb:30:in `initialize'
./main.rb:181:in `new'
./main.rb:181:in `run_demo_from_file'
./main.rb:319:in `block in run_application'
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:688:in `invoke'
/var/lib/gems/2.7.0/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:559:in `run'
./main.rb:518:in `<main>'
```

**Comment by kou** [comment]
Good catch!
I've fixed it.
