### ISSUE TITLE
FrozenError during <require 'gtk4'> : can't modify frozen Hash, in PangoCairo::FontMap.new_for_font_type 

### ISSUE THREAD

**Issue by spchamp** [ruby-gnome/ruby-gnome#1480]
Since today, I've begun noticing what looks like a deadlock in GIR when trying to initialize either the gtk3 or gtk4 modules from the Ruby-GNOME project. 

After updating the local GTK package installation to the latest local port build, I was still noticing a deadlock under the gtk3 gems, during Gtk.Init. This is on a FreeBSD 13.1 machine (local FreeBSD base system/kernel build, local ports build). I haven't noticed any errors from GTK apps on the desktop. I was not able to debug much of where it's deadlocking when trying to require gtk3. 

I've updated the local project to use gtk4 instead, and have noticed the following error now - a FrozenError under one section of the upstream code.

This is with a project in a directory `/opt/rbsource/rbthinkum/rbcommon/rblib/` using the latest gtk4 gems as installed with Bundler.

~~~~
/opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash: {"create_pa
ngo_context"=>#<GObjectIntrospection::Loader::Invoker:0x0000000809c233d0 @info=#<GObjectIntrospection::FunctionInfo:0x0000000809c23510 ptr=0x00000008089c38a0 own=true signature=<create_context
(cr: interface(CairoGObject::Context(CairoContext))): interface(Pango::Context(PangoContext))> name="create_context" arguments=[#<GObjectIntrospection::ArgInfo:0x0000000809c23290 ptr=0x0000000
8089b9320 own=true name="cr" optional?=false may_be_null?=false caller_allocates?=false type=#<GObjectIntrospection::TypeInfo:0x000000080beda540 ptr=0x000000080a75ce30 own=true tag=#<GObjectIn
trospection::TypeTag interface>>>] return_type=#<GObjectIntrospection::TypeInfo:0x000000080beda248 ptr=0x000000080a75ce80 own=true tag=#<GObjectIntrospection::TypeTag interface>> may_return_ty
pe_null=false lock_gvl_default=true>, @method_name="create_pango_context", @full_method_name="PangoCairo::CairoContextMethods#create_pango_context", @prepared=true, @in_args=[#<GObjectIntrospe
ction::ArgInfo:0x0000000809c23290 ptr=0x00000008089b9320 own=true name="cr" vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash: {"create_pa
ngo_context"=>#<GObjectIntrospection::Loader::Invoker:0x0000000809c233d0 @info=#<GObjectIntrospection::FunctionInfo:0x0000000809c23510 ptr=0x00000008089c38a0 own=true signature=<create_context
(cr: interface(CairoGObject::Context(CairoContext))): interface(Pango::Context(PangoContext))> name="create_context" arguments=[#<GObjectIntrospection::ArgInfo:0x0000000809c23290 ptr=0x0000000
8089b9320 own=true name="cr" optional?=false may_be_null?=false caller_allocates?=false type=#<GObjectIntrospection::TypeInfo:0x000000080beda540 ptr=0x000000080a75ce30 own=true tag=#<GObjectIn
trospection::TypeTag interface>>>] return_type=#<GObjectIntrospection::TypeInfo:0x000000080beda248 ptr=0x000000080a75ce80 own=true tag=#<GObjectIntrospection::TypeTag interface>> may_return_ty
pe_null=false lock_gvl_default=true>, @method_name="create_pango_context", @full_method_name="PangoCairo::CairoContextMethods#create_pango_context", @prepared=true, @in_args=[#<GObjectIntrospe
ction::ArgInfo:0x0000000809c23290 ptr=0x00000008089b9320 own=true name="cr"  [sic]...
~~~~

The following backtrace illustrates the FrozenError under `require 'gtk4'`.  

The local source tree that I'm working on here has been published to a repository at GitHub, though not with all the latest local changesets. I was trying to test out a next changeset for this source code, when I began noticing errors under the Gtk support for Ruby, with the local project configuration. 

A backtrace for the FrozenError that I'm seeing now as beginning approximately under `require 'gtk4'`. The following is in  using rdbg for the backtrace. The riview script is included below, illustrating how rdbg was called in this context.

~~~~
#-- ./bin/riview
#-- FreeBSD xt.cloud.thinkum.space 13.1-STABLE FreeBSD 13.1-STABLE #0 build/stable/13-n251001-41ce229505a: Sat Jun  4 18:12:09 PDT 2022     gimbal@sol.cloud.thinkum.space:/usr/obj/sol_FreeBSD-13.1-STABLE_amd64/usr/src/amd64.amd64/sys/RIPARIAN amd64
#-- /opt/rbsource/rbthinkum/rbcommon/rblib
#-- Tue Jun  7 19:39:21 PDT 2022
#-- /usr/local/bin/bash
[1, 10] in ./bin/riview
     1| #!
     2| 
=>   3| require %q(bundler/setup)
     4| 
     5| #require %q(irb)
     6| #require %q(irb/completion)
     7| 
     8| require %q(thinkum_space/project/y_spec)
     9| 
    10| yspec = ThinkumSpace::Project::YSpec.new(
=>#0	<main> at ./bin/riview:3
(rdbg:commands) break Gtk::Loader.initialize
uninitialized constant Gtk

Gtk::Loader
^^^
#0  BP - Method (pending)  Gtk::Loader.initialize
(rdbg:commands) break GObjectIntrospection::FunctionInfo#invoke
uninitialized constant GObjectIntrospection

GObjectIntrospection::FunctionInfo
^^^^^^^^^^^^^^^^^^^^
#1  BP - Method (pending)  GObjectIntrospection::FunctionInfo#invoke
(rdbg:commands) catch Gtk::InitError
#2  BP - Catch  "Gtk::InitError"
(rdbg:commands) catch FrozenError
#3  BP - Catch  "FrozenError"
(rdbg:commands) continue
DEBUGGER:  BP - Method  GObjectIntrospection::FunctionInfo#invoke at /usr/local/lib/ruby/gems/3.1/gems/debug-1.5.0/lib/debug/breakpoint.rb:453 is activated.
[681, 690] in /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb
   681| 
   682|         if block.nil? and @require_callback_p
   683|           receiver.to_enum(@method_name, *arguments)
   684|         else
   685|           if @function_info_p
=> 686|             return_value = @info.invoke(arguments, &block)
   687|           else
   688|             return_value = @info.invoke(receiver, arguments, &block)
   689|           end
   690|           if @have_return_value_p
=>#0	GObjectIntrospection::Loader::Invoker#invoke(receiver=nil, arguments=[], block=nil, abort_tag=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:686
  #1	Pango.version_string(arguments=[], block=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:112
  # and 19 frames (use `bt' command for all frames)

Stop by #1  BP - Method  GObjectIntrospection::FunctionInfo#invoke at /usr/local/lib/ruby/gems/3.1/gems/debug-1.5.0/lib/debug/breakpoint.rb:453
▽(rdbg) (rdbg) b    # break command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command=>#0	GObjectIntrospection::Loader::Invoker#invoke(receiver=nil, arguments=[], block=nil, abort_tag=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:686
  #1	Pango.version_string(arguments=[], block=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:112
  #2	<module:Version> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/version.rb:19
  #3	<module:Pango> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/version.rb:18
  #4	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/version.rb:17
  #5	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/loader.rb:95
  #6	Pango::Loader#require_libraries at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/loader.rb:95
  #7	Pango::Loader#post_load(repository=#<GObjectIntrospection::Repository:0x806..., namespace="Pango") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/loader.rb:34
  #8	block in load at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:49
  #9	GObjectIntrospection::Loader#prepare_class(klass=Pango) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:622
  #10	GObjectIntrospection::Loader#load(namespace="Pango") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:41
  #11	<module:Pango> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango.rb:32
  #12	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango.rb:27
  #13	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:20
  #14	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:20
  #15	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #16	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #17	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #18	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #19	[C] Kernel#require at ./bin/riview:28
  #20	<main> at ./bin/riview:28
(rdbg) (rdbg) c    # continue command(rdbg) c    # continue command(rdbg) c    # continue command[681, 690] in /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb
   681| 
   682|         if block.nil? and @require_callback_p
   683|           receiver.to_enum(@method_name, *arguments)
   684|         else
   685|           if @function_info_p
=> 686|             return_value = @info.invoke(arguments, &block)
   687|           else
   688|             return_value = @info.invoke(receiver, arguments, &block)
   689|           end
   690|           if @have_return_value_p
=>#0	GObjectIntrospection::Loader::Invoker#invoke(receiver=nil, arguments=[#<CairoGObject::FontType ft>], block=nil, abort_tag=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:686
  #1	PangoCairo::FontMap.new_for_font_type(arguments=[#<CairoGObject::FontType ft>], block=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:112
  # and 16 frames (use `bt' command for all frames)

Stop by #1  BP - Method  GObjectIntrospection::FunctionInfo#invoke at /usr/local/lib/ruby/gems/3.1/gems/debug-1.5.0/lib/debug/breakpoint.rb:453
(rdbg) (rdbg) b    # break command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command=>#0	GObjectIntrospection::Loader::Invoker#invoke(receiver=nil, arguments=[#<CairoGObject::FontType ft>], block=nil, abort_tag=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:686
  #1	PangoCairo::FontMap.new_for_font_type(arguments=[#<CairoGObject::FontType ft>], block=nil) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:112
  #2	block {|font_type=:ft|} in post_load at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/cairo-loader.rb:34
  #3	[C] Array#each at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/cairo-loader.rb:33
  #4	PangoCairo::Loader#post_load(repository=#<GObjectIntrospection::Repository:0x806..., namespace="PangoCairo") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango/cairo-loader.rb:33
  #5	block in load at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:49
  #6	GObjectIntrospection::Loader#prepare_class(klass=PangoCairo) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:622
  #7	GObjectIntrospection::Loader#load(namespace="PangoCairo") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:41
  #8	<module:PangoCairo> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango.rb:37
  #9	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/pango-3.5.1/lib/pango.rb:35
  #10	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:20
  #11	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:20
  #12	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #13	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #14	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #15	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #16	[C] Kernel#require at ./bin/riview:28
  #17	<main> at ./bin/riview:28
(rdbg) (rdbg) c    # continue command(rdbg) c    # continue command(rdbg) c    # continue command[550, 559] in /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb
   550|       return if method_name.empty?
   551|       prepare_function_info_lock_gvl(info, klass)
   552|       remove_existing_method(klass, method_name)
   553|       invoker = Invoker.new(info, method_name, "#{klass}\##{method_name}")
   554|       invokers = klass::INVOKERS
=> 555|       invokers[method_name] = invoker
   556|       klass.class_eval(<<-DEFINE_METHOD, __FILE__, __LINE__ + 1)
   557|         def #{method_name}(*arguments, &block)
   558|           invoker = INVOKERS["#{method_name}"]
   559|           invoker.invoke(self, arguments, block)
=>#0	GObjectIntrospection::Loader#define_method(info=#<GObjectIntrospection::FunctionInfo:0x0..., klass=Cairo::Context, method_name="draw_from_gl") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555
  #1	Gdk::Loader#load_function_info(info=#<GObjectIntrospection::FunctionInfo:0x0...) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4/loader.rb:73
  # and 19 frames (use `bt' command for all frames)

Stop by #3  BP - Catch  "FrozenError"
(rdbg) (rdbg) b    # break command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command(rdbg) bt    # backtrace command=>#0	GObjectIntrospection::Loader#define_method(info=#<GObjectIntrospection::FunctionInfo:0x0..., klass=Cairo::Context, method_name="draw_from_gl") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555
  #1	Gdk::Loader#load_function_info(info=#<GObjectIntrospection::FunctionInfo:0x0...) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4/loader.rb:73
  #2	GObjectIntrospection::Loader#load_info(info=#<GObjectIntrospection::FunctionInfo:0x0...) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:63
  #3	block {|info=#<GObjectIntrospection::FunctionInfo:0x0...|} in load (2 levels) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:47
  #4	block {|i=2387|} in each (2 levels) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:34
  #5	[C] Integer#times at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:33
  #6	block {|namespace="Gdk"|} in each at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:33
  #7	[C] Array#each at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:32
  #8	GObjectIntrospection::Repository#each(namespaces=["Gdk"]) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/repository.rb:32
  #9	block in load at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:46
  #10	GObjectIntrospection::Loader#prepare_class(klass=Gdk) at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:622
  #11	GObjectIntrospection::Loader#load(namespace="Gdk") at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:41
  #12	Gdk::Loader#load at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4/loader.rb:21
  #13	<module:Gdk> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:34
  #14	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gdk4-3.5.1/lib/gdk4.rb:26
  #15	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #16	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/vendor/bundle/ruby/3.1/gems/gtk4-3.5.1/lib/gtk4.rb:19
  #17	[C] Kernel#require at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #18	<top (required)> at /opt/rbsource/rbthinkum/rbcommon/rblib/lib/riview/riview_app.rb:27
  #19	[C] Kernel#require at ./bin/riview:28
  #20	<main> at ./bin/riview:28
(rdbg) 
~~~~

The riview shell script that I'm using, it runs ruby via bunder with some breakpoints and a couple of catch handlers activated:
~~~~
#!/usr/bin/env -S rdbg -e 'break Gtk::Loader.initialize' -e 'break GObjectIntrospection::FunctionInfo#invoke'  -e "catch Gtk::InitError" -e 'catch FrozenError' -e 'continue' -c bundle exec ruby

require %q(bundler/setup)

require %q(thinkum_space/project/y_spec)

## local gemspec initialization code for the project (partially published)
yspec = ThinkumSpace::Project::YSpec.new(
  ENV['PROJECT_YAML'] ||
    File.expand_path('project.yaml', File.dirname(ENV['BUNDLE_GEMFILE']))
)
yspec.load_config.gems.each do |name|
  ## ensuring each depended-on gemspec is initialized
  gem(name)
end

require 'debug'
require 'gobject-introspection'

## the following is where it calls "require 'gtk4'"
require 'riview/riview_app' 

##
# Local Variables:
# mode: enh-ruby
# End:
~~~~

This ruby shell script -- as installed locally at `bin/riview` under the project root dir -- it runs rdbg to run ruby under bundler, with breakpoints addded for the following:
- Gtk::Loader.initialize
- GObjectIntrospection::FunctionInfo#invoke

...and with a catch for each of the following:
- Gtk::InitError
- FrozenError

The breakpoints and the catch on Gtk::InitError were added when I was trying to debug the deadlock I'm seeing when  using the gtk3 gem insetad of gtk4.

This FrozenError that I"m seeing now might at least be more accessible than the deadlocak under GIR that I was seeing during 'Gtk.init' with the gtk3 gem. I wasn't able to produce any useful backtrace for that usage case. 

Candidly, I'm not even really certain of how helpful the previous backtrace could be. Presently, I'm at a loss to guess where to debug this - wherever the frozen data error could be occuring at a soruce level. 

There is that backtrace from rdbg at least?

The Ruby-GNOME gems were working out on the same development machine, just a couple of days ago. I'm not seeing any errors from C-based Gtk apps on the desktop, today. The only thing that has changed on the machine in this duration is that I've upgraded to a newer local kernel and base system build (FreeBSD) and updated the local kmod pacakges (intel GPU support ported for the FreeBSD kernel). I'd not been seeing any deadlock with the ruby-GNOME gems -- mainly gtk3 -- before this time. I was able to initialize a basic GUI app with the local source code, 

I wasn't able to produce a backtrace for the dedlock I'm seeing under Gtk.init. Maybe anyone else can help to figure out how to address this FrozenError at lesat?

I'll try to test this on a different platform - I have access to an openSUSE installation under bhyve (uefi), it has a full Cinnamon desktop installed there. 

Considering that it should not be a very difficult gemspec configuration to port from the local YAML-based config, I'll try to develop an independent test case, using only the ruby-GNOME gems via a script for bundler, to simply require gtk4

Certainly, someone has been able to `require 'gtk4'` under some host/app configuration

**Comment by spchamp** [comment]
I've published a source repository for a stand-alone test case to the effect of this error I'm seeing: [rubyblox/gtk_test](https://github.com/rubyblox/gtk_test)

Testing the code like as follows, I'm seeing the same FrozenError:
~~~~
## at the BASH shell
$ git clone https://github.com/rubyblox/gtk_test.git gtk_test && cd gtk_test
$ bundle install
$ bundle exec irb
## in irb, subsequently
irb(main):001:0> require 'gtk4'                                                                                                                                                                 
/usr/local/lib/ruby/gems/3.1/gems/gobject-introspection-3.5.1/lib/gobject-introspection/loader.rb:555:in `define_method': can't modify frozen Hash: {"create_pango_context"=># [_sic_]
~~~~

This is on the same development machine, where `uname -a` shows the following:
~~~~
FreeBSD xt.cloud.thinkum.space 13.1-STABLE FreeBSD 13.1-STABLE #0 build/stable/13-n251001-41ce229505a: Sat Jun  4 18:12:09 PDT 2022     username@hostname:/usr/obj/sol_FreeBSD-13.1-STABLE_amd64/usr/src/amd64.amd64/sys/RIPARIAN amd64
~~~~

**Comment by kou** [comment]
I'm working on this. Sorry.

See also: https://github.com/ruby-gnome/ruby-gnome/pull/1474, https://github.com/ruby-gnome/ruby-gnome/issues/1455 (duplicated)

**Comment by spchamp** [comment]
I'll focus on GTK 3 then.

fwiw I discovered that the deadlock I was seeing when using gtk3 was probably a side effect of DISPLAY not being set in the process environment - such as when running ruby under an emacs process started from a server script, or in a tmux session created before running startx. 

After taking a look at the system calls with ruby running under gdb, it showed that something was trying to make a socket connection after I'd tried to dereference the class Gtk::Application. After ensuring that the DISPLAY environment variable is set in the Ruby process environment, the Gtk::Application class can be dereferenced and used as a superclass then.

**Comment by kou** [comment]
OK. Could you update the title or create another issue?

**Comment by spchamp** [comment]
If it could be of any help? I don't believe that's any bug though. In the gdb output, it looks like the call to open a socket might be originating from gdk_display_manager_open_display. I understand that Gtk.init might be called at some point. As closure to the remark that it was hanging up under gtk3, i'll add a check to my own code to warn if DISPLAY is not set

**Comment by kou** [comment]
Your problem is caused by no `DISPLAY` and it's your problem not library problem, right?

**Comment by spchamp** [comment]
It looks like it's due to something in GDK. I've developed a workaround. Did not want to open a second ticket for the item, no worries
