### ISSUE TITLE
Deprecation warning for gtk4, in the file "hello_world.rb", 32

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1489]
Hey there kou,

This is just info. I am noticing you made some changes to ruby-gnome lately.

I just did "git clone ruby-gnome" (well, the last part is the URL to the repository here),
so I run the latest code. Then I did "rake" for the Rakefile. Good news: it seems to 
work now via rake too. I think it did not for me some months before. Anyway.

When trying to run hello_world.rb from:

    ruby-gnome/gtk4/sample/hello_world.rb

I now get this error:

    /Depot/jjj/ruby-gnome/glib2/lib/glib2/deprecatable.rb:127:in `const_missing': hello_world.rb:32:in `block in <main>': 'Gtk::ButtonBox' has been deprecated. Don't use this class.
             from hello_world.rb:32:in `block in <main>'
             from /Depot/jjj/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:688:in `invoke'
             from /Depot/jjj/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:688:in `invoke'
             from /Depot/jjj/ruby-gnome/gobject-introspection/lib/gobject-introspection/loader.rb:559:in `run'
             from hello_world.rb:46:in `<main>'

So perhaps there was a change between ruby-gtk3 and ruby-gtk4. Just reporting this here so you can keep track
of any deprecation changes. (I myself don't know what has been deprecated so far, so this is the first 
deprecation notice I actually see in ruby gtk4)

Happy ruby-gnoming!

**Comment by kou** [comment]
I'm working on `gtk4/lib/` and `gtk4/test/` and it'll be complemented soon.
But there are many incompatible changes in GTK4: https://docs.gtk.org/gtk4/migrating-3to4.html

We need to update `gtk4/sample/` too but there are many scripts for it.
I want help from Ruby-GNOME community to update `gtk4/sample/`.
We need to port the followings to Ruby from C:
* https://gitlab.gnome.org/GNOME/gtk/-/tree/main/examples
* https://gitlab.gnome.org/GNOME/gtk/-/tree/main/demos
* https://gitlab.gnome.org/GNOME/gtk/-/blob/main/docs/reference/gtk/getting_started.md

See also:
* https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/sample/examples/README.md
* https://github.com/ruby-gnome/ruby-gnome/tree/master/gtk4/sample/demos/README.md
* https://github.com/ruby-gnome/ruby-gnome/blob/master/gtk4/sample/getting-started/README.md

It's better that we also have a migration guide like GTK: https://docs.gtk.org/gtk4/migrating-3to4.html
We can put it to `gtk4/doc/migration.md` for now. We can integrate the file to our document build system ( https://github.com/ruby-gnome/ruby-gnome/blob/master/.github/workflows/doc.yml#L29-L38 ) later.

Do you want to take the initiative of this "update `gtk4/sample/`" subproject? Or do you know people who want to do it?

**Comment by spchamp** [comment]
I'd be interested in helping out with this, in a long term. Perhaps the effort could be aided with some experience in porting an app from GTK3 with Ruby-GNOME to GTK4 with Ruby-GNOME? 

I don't believe I have any complete GTK 3 app, as yet. On the topic of porting from GTK3 to GTK4, personally I'm working on a [terminal emulator](https://github.com/rubyblox/pebbl_app/blob/main/lib/vty.rb) (and [UI files](https://github.com/rubyblox/pebbl_app/tree/main/ui)) that uses Ruby-GNOME in GTK 3 - but not to hijack this thread for describing the project lol. Before I could say it's a complete app, it will need support for users preferences / terminal profiles at least.

If one may introduce a separate topic, I'd like to add support for developing Glade catalogs in Ruby, perhaps something in a manner of Glade's python support. I believe that it would be entirely a separate project however. 

Perhaps the glade support has not changed much in GTK 4?

**Comment by kou** [comment]
Thanks for your response.
You want to work on the "update `gtk4/sample/`" subproject, right?

**Comment by anatol** [comment]
There is a similar issue with other examples:

```
➜  examples git:(master) ./drawing.rb 
/usr/lib/ruby/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/deprecatable.rb:127:in `const_missing': ./drawing.rb:64:in `block in <main>': 'Gtk::ShadowType' has been deprecated. Don't use this class.
	 from ./drawing.rb:64:in `block in <main>'
	 from /usr/lib/ruby/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:688:in `invoke'
	 from /usr/lib/ruby/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:688:in `invoke'
	 from /usr/lib/ruby/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:559:in `run'
	 from ./drawing.rb:121:in `<main>'
```

**Comment by viseztrance** [comment]
> Thanks for your response. You want to work on the "update `gtk4/sample/`" subproject, right?

If there's nobody else already working on this, I can update the samples folder.

**Comment by kou** [comment]
Great!!!
