### ISSUE TITLE
Segfault on gstreamer after calling p sample.buffer.map(1).data

### ISSUE THREAD

**Issue by jvmf1** [ruby-gnome/ruby-gnome#1524]
```ruby
require 'gstreamer'

pipeline, ok = Gst.parse_launch('videotestsrc ! videoconvert ! videorate ! video/x-raw,framerate=5/1 ! jpegenc quality=50 ! appsink drop=true sync=false name=sink max-buffers=1')
p pipeline

sink = pipeline.get_by_name('sink')

pipeline.play

loop do
  sample = sink.try_pull_sample(Gst::SECOND * 5)
  next unless sample

  buf = sample.buffer
  ok, map = buf.map(1)
  next unless ok

  p map.data
  buf.unmap(map)
end
```

```
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:283: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0030 e:000029 CFUNC  :get_field_value
c:0005 p:0008 s:0024 e:000023 BLOCK  /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:283 [FINISH]
c:0004 p:0058 s:0020 e:000019 BLOCK  ruby.rb:18 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :loop
c:0002 p:0055 s:0009 E:0020c8 EVAL   ruby.rb:12 [FINISH]
c:0001 p:0000 s:0003 E:000af0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ruby.rb:12:in `<main>'
ruby.rb:12:in `loop'
ruby.rb:18:in `block in <main>'
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:283:in `block in load_field_reader'
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb:283:in `get_field_value'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fbd9daee9bb RBP: 0xffffffffffffffff RSP: 0x00007ffcb8f02390
 RAX: 0x0000000000000003 RBX: 0x000055c7d65298e0 RCX: 0x0000000000000000
 RDX: 0x00007ffcb8f02630 RDI: 0x000055c7d7219e80 RSI: 0x0000000000000000
  R8: 0x0000000000000001  R9: 0x00000000000048a0 R10: 0x000000000000000b
 R11: 0x0000000000000050 R12: 0x000055c7d7219e80 R13: 0x00007ffcb8f024d0
 R14: 0x0000000000000002 R15: 0x00007fbda134eef8 EFL: 0x0000000000010213

-- C level backtrace information -------------------------------------------
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(0x7fbda1efb0e0) [0x7fbda1efb0e0]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(0x7fbda1d4f504) [0x7fbda1d4f504]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(0x7fbda1e6f4fd) [0x7fbda1e6f4fd]
/lib/x86_64-linux-gnu/libc.so.6(__restore_rt+0x0) [0x7fbda1aca520]
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject_introspection.so(rb_gi_arguments_convert_arg_array_body+0x3b) [0x7fbd9daee9bb]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_ensure+0x126) [0x7fbda1d56c16]
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject_introspection.so(rb_gi_arguments_convert_arg+0x20f) [0x7fbd9daf0bbf]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_ensure+0x126) [0x7fbda1d56c16]
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject_introspection.so(rb_gi_field_info_get_field_raw+0x80) [0x7fbd9daf33e0]
/var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject_introspection.so(rg_get_field_value+0x4c) [0x7fbd9daf752c]
[0x7fbda1edfc45]
[0x7fbda1ee1fd6]
[0x7fbda1ee4c42]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_vm_exec+0x1fd) [0x7fbda1eea31d]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_vm_invoke_bmethod+0x272) [0x7fbda1eeb5b2]
[0x7fbda1eebcb2]
[0x7fbda1ee1fd6]
[0x7fbda1ee4c42]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_vm_exec+0x1fd) [0x7fbda1eea31d]
[0x7fbda1eed538]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_vrescue2+0x11e) [0x7fbda1d5655e]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_rescue2+0x8e) [0x7fbda1d567ee]
[0x7fbda1edfc45]
[0x7fbda1ee1fd6]
[0x7fbda1ee4ca7]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(rb_vm_exec+0x1fd) [0x7fbda1eea31d]
[0x7fbda1d55328]
/lib/x86_64-linux-gnu/libruby-3.0.so.3.0(ruby_run_node+0x5a) [0x7fbda1d58e2a]
[0x55c7d5d3317f]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_call_main+0x80) [0x7fbda1ab1d90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7fbda1ab1e40]
/usr/bin/ruby3.0(_start+0x25) [0x55c7d5d331c5]

-- Other runtime information -----------------------------------------------

* Loaded script: ruby.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 ruby2_keywords.rb
    5 /usr/lib/x86_64-linux-gnu/ruby/3.0.0/enc/encdb.so
    6 /usr/lib/x86_64-linux-gnu/ruby/3.0.0/enc/trans/transdb.so
    7 /usr/lib/x86_64-linux-gnu/ruby/3.0.0/rbconfig.rb
    8 /usr/lib/ruby/vendor_ruby/rubygems/compatibility.rb
    9 /usr/lib/ruby/vendor_ruby/rubygems/defaults.rb
   10 /usr/lib/ruby/vendor_ruby/rubygems/deprecate.rb
   11 /usr/lib/ruby/vendor_ruby/rubygems/errors.rb
   12 /usr/lib/ruby/vendor_ruby/rubygems/unknown_command_spell_checker.rb
   13 /usr/lib/ruby/vendor_ruby/rubygems/exceptions.rb
   14 /usr/lib/ruby/vendor_ruby/rubygems/basic_specification.rb
   15 /usr/lib/ruby/vendor_ruby/rubygems/stub_specification.rb
   16 /usr/lib/ruby/vendor_ruby/rubygems/platform.rb
   17 /usr/lib/ruby/vendor_ruby/rubygems/version.rb
   18 /usr/lib/ruby/vendor_ruby/rubygems/requirement.rb
   19 /usr/lib/ruby/vendor_ruby/rubygems/util/list.rb
   20 /usr/lib/ruby/vendor_ruby/rubygems/specification.rb
   21 /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb
   22 /usr/lib/ruby/vendor_ruby/rubygems/util.rb
   23 /usr/lib/ruby/vendor_ruby/rubygems/dependency.rb
   24 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_gem.rb
   25 /usr/lib/x86_64-linux-gnu/ruby/3.0.0/monitor.so
   26 /usr/lib/ruby/3.0.0/monitor.rb
   27 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb
   28 /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_warn.rb
   29 /usr/lib/ruby/vendor_ruby/rubygems.rb
   30 /usr/lib/ruby/vendor_ruby/rubygems/path_support.rb
   31 /usr/lib/ruby/3.0.0/did_you_mean/version.rb
   32 /usr/lib/ruby/3.0.0/did_you_mean/core_ext/name_error.rb
   33 /usr/lib/ruby/3.0.0/did_you_mean/levenshtein.rb
   34 /usr/lib/ruby/3.0.0/did_you_mean/jaro_winkler.rb
   35 /usr/lib/ruby/3.0.0/did_you_mean/spell_checker.rb
   36 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   37 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   38 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers.rb
   39 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/method_name_checker.rb
   40 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/key_error_checker.rb
   41 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/null_checker.rb
   42 /usr/lib/ruby/3.0.0/did_you_mean/tree_spell_checker.rb
   43 /usr/lib/ruby/3.0.0/did_you_mean/spell_checkers/require_path_checker.rb
   44 /usr/lib/ruby/3.0.0/did_you_mean/formatters/plain_formatter.rb
   45 /usr/lib/ruby/3.0.0/did_you_mean.rb
   46 /usr/lib/ruby/3.0.0/English.rb
   47 /usr/lib/x86_64-linux-gnu/ruby/3.0.0/pathname.so
   48 /usr/lib/ruby/3.0.0/pathname.rb
   49 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/deprecatable.rb
   50 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2.so
   51 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/version.rb
   52 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/deprecated.rb
   53 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/date-time.rb
   54 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/regex.rb
   55 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2/variant.rb
   56 /var/lib/gems/3.0.0/gems/glib2-4.0.3/lib/glib2.rb
   57 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject_introspection.so
   58 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/arg-info.rb
   59 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/collection-reader.rb
   60 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/boxed-info.rb
   61 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/callable-info.rb
   62 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/function-info.rb
   63 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/interface-info.rb
   64 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/object-info.rb
   65 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/registered-type-info.rb
   66 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/repository.rb
   67 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/struct-info.rb
   68 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/type-info.rb
   69 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/type-tag.rb
   70 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/union-info.rb
   71 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/version.rb
   72 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection/loader.rb
   73 /var/lib/gems/3.0.0/gems/gobject-introspection-4.0.3/lib/gobject-introspection.rb
   74 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/loader.rb
   75 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/base-loader.rb
   76 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/controller-loader.rb
   77 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst.rb
   78 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gstreamer.rb
   79 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gstreamer.so
   80 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/bin.rb
   81 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/bus.rb
   82 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/caps.rb
   83 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/element.rb
   84 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/element-factory.rb
   85 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/plugin-feature.rb
   86 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/registry.rb
   87 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/structure.rb
   88 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/tag-list.rb
   89 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/type-find-factory.rb
   90 /var/lib/gems/3.0.0/gems/gstreamer-4.0.3/lib/gst/version.rb
```

**Comment by kou** [comment]
Thanks for your report.
I've added support for getting field value that has separated length field.
