### ISSUE TITLE
gstreamer would not be build

### ISSUE THREAD

**Issue by D-W-L** [ruby-gnome/ruby-gnome#1540]
At compile `extconf.rb` gives the following error message
```
╭─det at zoo in /home/det/Schreibtisch/soft/ruby-gnome/gstreamer (master ✔)
╰─λ ruby extconf.rb                                                                                                                     0 (0.004s)
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... yes
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... no
checking for -Wunsafe-loop-optimizations option to compiler... yes
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... no
checking for gstreamer-1.0... yes
*** /home/det/Schreibtisch/soft/ruby-gnome/gstreamer/ext/gstreamer/extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=/home/det/Schreibtisch/soft/ruby-gnome/gstreamer/ext/gstreamer
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--enable-debug-build
	--disable-debug-build
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:389:in `parse_pc': .pc doesn't exist: <libunwind> (PackageConfig::NotFoundError)
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:233:in `declaration'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:178:in `requires_private'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:509:in `block in all_required_packages'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:259:in `collect_requires'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:508:in `all_required_packages'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:283:in `collect_cflags'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:191:in `cflags_only_other'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:569:in `cflags_only_other'
	from /usr/local/lib/ruby/gems/3.2.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:616:in `have_package'
	from /home/det/Schreibtisch/soft/ruby-gnome/glib2/lib/mkmf-gnome.rb:477:in `required_pkg_config_package'
	from /home/det/Schreibtisch/soft/ruby-gnome/gstreamer/ext/gstreamer/extconf.rb:41:in `<main>'
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
```
It seems to me, that in `gstreamer/ext/gstreamer` the `ruby-gstreamer.pc` file is missing

**Comment by D-W-L** [comment]
I have `libunwind-14-dev` installed. If I try to install `libunwind.dev`, apt would de-install `libunwind-14.dev` and `libc++-14.dev`. That is not an option for me.
I don't need the gstreamer package, but there may be others who are, and I thought that there may be an other solution.

**Comment by kou** [comment]
Removing `libunwind, ` from `Requires.private` in `/usr/lib/x86_64-linux-gnu/pkgconfig/gstreamer-1.0.pc` may work.

**Comment by D-W-L** [comment]
Thank you!
