### ISSUE TITLE
ruby-gtk4: test fails with gtk 4.9.3

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1548]
Hello:

I just rushed into report this issue that I've noticed that ruby-gtk4 4.1.1 (as well as 396d2d377bd85d9bdd73b26210e323129deea1f4 ) test suite fails with gtk 4.9.3 as:

```
.........................................................E
===============================================================================
Error: test: :data(TestGtkCssProvider::#load): ArgumentError: Gtk::CssProvider#load_from_data: wrong number of arguments (1 for 2)
/usr/share/gems/gems/gobject-introspection-4.1.0/lib/gobject-introspection/loader.rb:675:in `invoke'
/usr/share/gems/gems/gobject-introspection-4.1.0/lib/gobject-introspection/loader.rb:559:in `load_from_data'
/builddir/build/BUILD/gtk4-4.1.1/usr/share/gems/gems/gtk4-4.1.1/lib/gtk4/css-provider.rb:43:in `load_from_data'
/builddir/build/BUILD/gtk4-4.1.1/usr/share/gems/gems/gtk4-4.1.1/lib/gtk4/css-provider.rb:25:in `load'
/builddir/build/BUILD/gtk4-4.1.1/usr/share/gems/gems/gtk4-4.1.1/test/test-gtk-css-provider.rb:27:in `block (3 levels) in <class:TestGtkCssProvider>'
<internal:trace_point>:262:in `enable'
<internal:trace_point>:262:in `enable'
/builddir/build/BUILD/gtk4-4.1.1/usr/share/gems/gems/gtk4-4.1.1/test/test-gtk-css-provider.rb:26:in `block (2 levels) in <class:TestGtkCssProvider>'
===============================================================================
```

With gtk 4.8.3, test passes (i.e. no test failure).

I think the relevant change is this:
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5441
While I don't know how gobject-introspection interprets annotation, however with this MR annotation for `gtk_css_provider_load_from_data` changed. I don't know if this change is proper or not.

**Comment by kou** [comment]
Thanks!

**Comment by mtasaka** [comment]
Confirmed fixed, thank you.

**Comment by kou** [comment]
Thanks for confirming it.
I'll release a new version after we fix CI failures on macOS.
