### ISSUE TITLE
The specified procedure could not be found glib2.so (LoadError)

### ISSUE THREAD

**Issue by atha10** [ruby-gnome/ruby-gnome#1570]
```text
rails s
Traceback (most recent call last):
        42: from bin/rails:9:in `<main>'
        41: from bin/rails:9:in `require'
        40: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands.rb:18:in `<top (required)>'
        39: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command.rb:46:in `invoke'
        38: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/command/base.rb:69:in `perform'
        37: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        36: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        35: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        34: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `perform'
        33: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:138:in `tap'    
        32: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/railties-6.0.3.4/lib/rails/commands/server/server_command.rb:141:in `block in perform'
        31: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
        30: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        29: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        28: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
        27: from G:/Internship/DriveLms/dev/config/application.rb:10:in `<top (required)>'
        26: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler.rb:174:in `require'
        25: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        24: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        23: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
        22: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
        21: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
        20: from C:/Ruby27-x64/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
        19: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/ruby-gnome-72fabd5a6d6b/gtk3/lib/gtk3.rb:17:in `<top (required)>'    
        18: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
        17: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        16: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        15: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
        14: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/ruby-gnome-72fabd5a6d6b/atk/lib/atk.rb:17:in `<top (required)>'      
        13: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/ruby-gnome-72fabd5a6d6b/gobject-introspection/lib/gobject-introspection.rb:17:in `<top (required)>'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/ruby-gnome-72fabd5a6d6b/glib2/lib/glib2.rb:117:in `<top (required)>' 
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require'    
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:291:in `load_dependency'
         1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `block in require'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.4/lib/active_support/dependencies.rb:324:in `require': 127: The specified procedure could not be found.   - C:/Ruby27-x64/lib/ruby/gems/2.7.0/bundler/gems/ruby-gnome-72fabd5a6d6b/glib2/lib/glib2.so (LoadError)
```

**Comment by kou** [comment]
`ridk exec pacman -Syu` or updating your Ruby may solve this.

**Comment by kou** [comment]
No response.
