### ISSUE TITLE
Event controller GestureClick stops working

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1579]
There's a bug, but I'm not sure if it is in my code, ruby-gnome or GTK. Anyway, here's the somewhat confusing description:

My situation is that I have GtkSource::View, to which I attach GestureClick event controller. I want to detect where a mouse click on the screen happened and then update cursor position in the buffer accordingly. So, I first click on screen and then move cursor with keyboard to confirm new position.
```
    click = Gtk::GestureClick.new
    click.set_propagation_phase(Gtk::PropagationPhase::CAPTURE)
    self.add_controller(click)
    # Detect mouse click
    click.signal_connect "pressed" do |gesture, n_press, x, y, z|
      debug "SourceView, GestureClick"
      winw = width
      view_width = visible_rect.width
      gutter_width = winw - view_width
      i = get_iter_at_location((x - gutter_width).to_i, y.to_i)
      if !i.nil?
        @bufo.set_pos(i.offset)
      else
        debug "iter nil 0000"
      end
      true
    end
```

This works fine for a while after starting the program, but at some point after repeating 30+ times, it breaks down in random ways. Sometimes the GestureClick just stops receiving events. Sometimes the x,y position starts to get mapped to wrong place (higher on y-axis). Couple times I've got error messages from gobject-introspection/loader.rb (attached below). I had also similar issues where Gtk::EventControllerKey suddenly stopped working. Gtk version 4.6.9+ds-0ubuntu0.22.04.1. 

The source of relevant files in my software:
https://github.com/SamiSieranoja/vimamsa/blob/85383f79207a03800654baf463a42500f7656650/lib/vimamsa/gui_sourceview.rb
https://github.com/SamiSieranoja/vimamsa/blob/85383f79207a03800654baf463a42500f7656650/lib/vimamsa/gui.rb

I'm grateful for any help with this.

```
Gtk-CRITICAL **: gtk_render_node_paintable_new: assertion 'GSK_IS_RENDER_NODE (node)' failed
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `run'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:759:in `init_window'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:258:in `run'
	from exe/vimamsa:42:in `<main>'

(ruby:19132): Gsk-CRITICAL **: 16:58:16.192: gsk_render_node_unref: assertion 'GSK_IS_RENDER_NODE (node)' failed
GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `run'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:759:in `init_window'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:258:in `run'
	from exe/vimamsa:42:in `<main>'
```

```
GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkEventController'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `place_cursor'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui_sourceview.rb:262:in `set_cursor_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:182:in `gui_set_cursor_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/buffer.rb:834:in `set_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/buffer.rb:1016:in `move'
	from (eval):1:in `exec_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:522:in `eval'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:522:in `exec_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:472:in `block in handle_key_bindigs_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:471:in `times'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:471:in `handle_key_bindigs_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:364:in `match_key_conf'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui_sourceview.rb:186:in `handle_key_event'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:570:in `block in reset_controllers'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `run'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:759:in `init_window'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:258:in `run'
	from exe/vimamsa:42:in `<main>'
Gtk-CRITICAL **: gtk_event_controller_reset: assertion 'GTK_IS_EVENT_CONTROLLER (controller)' failed
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `place_cursor'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui_sourceview.rb:262:in `set_cursor_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:182:in `gui_set_cursor_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/buffer.rb:834:in `set_pos'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/buffer.rb:1016:in `move'
	from (eval):1:in `exec_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:522:in `eval'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:522:in `exec_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:472:in `block in handle_key_bindigs_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:471:in `times'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:471:in `handle_key_bindigs_action'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/key_binding_tree.rb:364:in `match_key_conf'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui_sourceview.rb:186:in `handle_key_event'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:570:in `block in reset_controllers'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:688:in `invoke'
	from /var/lib/gems/3.0.0/gems/gobject-introspection-4.1.1/lib/gobject-introspection/loader.rb:559:in `run'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:759:in `init_window'
	from /home/samsam/Drive/code/vimamsa2/git3/lib/vimamsa/gui.rb:258:in `run'
	from exe/vimamsa:42:in `<main>'
```

**Comment by SamiSieranoja** [comment]
Seems that there was a bug in my code. I forgot to add visible_rect.y to the y value for get_iter_at_location. But the GestureClick controller still dies randomly after a while, without any error messages.

**Comment by kou** [comment]
Does this work?

```diff
diff --git a/lib/vimamsa/gui_sourceview.rb b/lib/vimamsa/gui_sourceview.rb
index 4607479..8167eb8 100644
--- a/lib/vimamsa/gui_sourceview.rb
+++ b/lib/vimamsa/gui_sourceview.rb
@@ -22,6 +22,7 @@ class VSourceView < GtkSource::View
     debug "vsource init"
     @last_keyval = nil
     @last_event = [nil, nil]
+    @clicks = []
     self.highlight_current_line = true
 
     #    self.drag_dest_add_image_targets #TODO:gtk4
@@ -64,24 +65,29 @@ class VSourceView < GtkSource::View
   end
 
   def remove_old_controllers
-    clist = self.observe_controllers
-    to_remove = []
-    (0..(clist.n_items - 1)).each { |x|
-      ctr = clist.get_item(x)
-      if ctr.class == Gtk::EventControllerKey or ctr.class == Gtk::GestureClick
-        to_remove << ctr
-      end
-    }
-    if to_remove.size > 0
-      puts "Removing controllers:"
-      pp to_remove
-      to_remove.each { |x| self.remove_controller(x) }
+    # clist = self.observe_controllers
+    # to_remove = []
+    # (0..(clist.n_items - 1)).each { |x|
+    #   ctr = clist.get_item(x)
+    #   if ctr.class == Gtk::EventControllerKey or ctr.class == Gtk::GestureClick
+    #     to_remove << ctr
+    #   end
+    # }
+    # if to_remove.size > 0
+    #   puts "Removing controllers:"
+    #   pp to_remove
+    #   to_remove.each { |x| self.remove_controller(x) }
+    # end
+    @clicks.each do |click|
+      remove_controller(click)
     end
+    @clicks.clear
   end
 
   def register_signals()
     remove_old_controllers
     click = Gtk::GestureClick.new
+    @clicks << click
     click.set_propagation_phase(Gtk::PropagationPhase::CAPTURE)
     self.add_controller(click)
     # Detect mouse click
```

**Comment by kou** [comment]
`@clicks << click` is the key point.
`click` is GC-ed by Ruby without it but the block of `click.signal_connect "pressed"` is called after `click` was GC-ed. It causes the SEGV.
I think that Ruby-GNOME should avoid the GC automatically but I don't have a good idea to implement it for now. I'll add the following code if I can't come up with a better idea by the next release:

```diff
diff --git a/gtk4/lib/gtk4/widget.rb b/gtk4/lib/gtk4/widget.rb
index 99dddc1b9..46fbe89b9 100644
--- a/gtk4/lib/gtk4/widget.rb
+++ b/gtk4/lib/gtk4/widget.rb
@@ -94,6 +94,20 @@ module Gtk
       end
     end
 
+    alias_method :add_controller_raw, :add_controller
+    def add_controller(controller)
+      result = add_controller_raw(controller)
+      (@controllers ||= []) << controller
+      result
+    end
+
+    alias_method :remove_controller_raw, :remove_controller
+    def remove_controller(controller)
+      result = remove_controller_raw(controller)
+      (@controllers ||= []).delete(controller)
+      result
+    end
+
     def children
       _children = []
       child = first_child
```

**Comment by SamiSieranoja** [comment]
Oh, I didn't think about the GC. This helps actually, thanks!
