### ISSUE TITLE
gstreamer segfaults from Gst::Bitmask.signals

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1580]
I was trying to generate documentation to detect which signals exist for which classes. This seemed to work ok generally, but I got a segfault in case of Gst::Bitmask. gstreamer-4.2.0

```
require "gst"
Gst::Bitmask.signals
GLib-GObject-CRITICAL **: g_signal_list_ids: assertion 'G_TYPE_IS_INSTANTIATABLE (itype) || G_TYPE_IS_INTERFACE (itype)' failed
	from (irb):2:in `<top (required)>'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb/workspace.rb:117:in `eval'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb/workspace.rb:117:in `evaluate'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb/context.rb:525:in `evaluate'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:554:in `block (2 levels) in eval_input'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:870:in `signal_status'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:547:in `block in eval_input'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:628:in `block in each_top_level_statement'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:623:in `loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:623:in `each_top_level_statement'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:546:in `eval_input'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:502:in `block in run'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:501:in `catch'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:501:in `run'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/lib/irb.rb:409:in `start'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/irb-1.8.1/exe/irb:9:in `<top (required)>'
	from /home/samsam/.rbenv/versions/3.1.3/bin/irb:25:in `load'
	from /home/samsam/.rbenv/versions/3.1.3/bin/irb:25:in `<main>'
(irb):2: [BUG] Segmentation fault at 0x0000000000000000
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]

```

**Comment by kou** [comment]
Good catch!
It seems that we don't need to define a class for `Gst::Bitmask` (a fundamental `GType`).
