### ISSUE TITLE
Unable to implement ListModel interface

### ISSUE THREAD

**Issue by anna328p** [ruby-gnome/ruby-gnome#1585]
I'm using Ruby/GTK4. I'm trying to use a `ColumnView` with a custom `ListModel`. However, no matter how I try, I cannot seem to get my class to be recognized as a `ListModel`.

Minimal reproducible example: the provided code from [this issue comment](https://github.com/ruby-gnome/ruby-gnome/pull/1398#issuecomment-839802024), only changing `require 'gtk3'` to `require 'gtk4'`:

`test.rb`  
```ruby
require 'gtk4'

class Model < GLib::Object
  include Gio::ListModel

  type_register

  def initialize
    super

    @array = ["apple", "banana", "orange"] * 10
  end

  def virtual_do_get_item_type
    GLib::STRING
  end

  def virtual_do_get_n_items
    @array.length
  end

  def virtual_do_get_item(pos)
    @array[pos]
  end
end

listbox = Gtk::ListBox.new
model = Model.new
listbox.bind_model model do |item|
  Gtk::Label.new item
end

window = Gtk::Window.new
window << listbox
window.show_all

Gtk.main
```

Output:
`ruby test.rb`  
```
[...]/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke': must be <GListModel> object: <#<Model:0x00007f43d3fa55a0>> (ArgumentError)

            return_value = @info.invoke(receiver, arguments, &block)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from [...]/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke'
        from [...]/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:573:in `bind_model'
        from test.rb:29:in `<main>'
```

**Comment by kou** [comment]
* You need to call `type_register` before `include Gio::ListModel`
* You need to return a `GLib::Object` instead of `String` in `Model#virtual_do_get_item`

```ruby
require 'gtk4'

class ModelItem < GLib::Object
  type_register

  attr_reader :value
  def initialize(value)
    super()
    @value = value
  end
end

class Model < GLib::Object
  type_register

  include Gio::ListModel

  def initialize
    super

    @array = ["apple", "banana", "orange"] * 10
  end

  def virtual_do_get_item_type
    GLib::STRING
  end

  def virtual_do_get_n_items
    @array.length
  end

  def virtual_do_get_item(pos)
    ModelItem.new(@array[pos])
  end
end

app = Gtk::Application.new("org.gtk.example", :flags_none)

app.signal_connect "activate" do
  window = Gtk::ApplicationWindow.new(app)
  window.application = app

  listbox = Gtk::ListBox.new
  model = Model.new
  listbox.bind_model model do |item|
    Gtk::Label.new item.value
  end
  window.set_child(listbox)
  window.show
end

app.run
```

**Comment by kou** [comment]
I close this because there is no update.

**Comment by anna328p** [comment]
This worked. Thank you.
