### ISSUE TITLE
Crash from using gstreamer

### ISSUE THREAD

**Issue by SamiSieranoja** [ruby-gnome/ruby-gnome#1586]
I followed this example to implement audio playback:
https://github.com/ruby-gnome/ruby-gnome/blob/master/gstreamer/sample/helloworld.rb

The main part of my implementation is here:
https://github.com/SamiSieranoja/vimamsa/blob/e671e4e37d29f4498c4c5d1f194ba3682ce4066f/lib/vimamsa/audio.rb

This works fine otherwise, but sometimes after around 10-30 times playing different audio files, the program randomly crashes during playback due to segfault or some other error. Usually it happens right after starting playback.

Here is a long segfault error message:
https://gist.github.com/SamiSieranoja/8e9bf8db0abdfc8d86cfc37afe605397

Below is a shorter error message of same situation where segfault didn't happen, but another type of crash.

I tried to add rescue Exception for the line "return_value = @info.invoke(receiver, arguments, &block)" and investigate with ripl, but it crashed anyway. Not sure how I should debug this further. 

```
/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke': undefined method `call' for {:in=>nil}:Hash

              return_value = @info.invoke(receiver, arguments, &block)
                                  ^^^^^^^
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:575:in `run'
	 from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:737:in `init_window'
	 from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:200:in `run'
	 from exe/vimamsa:39:in `<main>'
/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit': exit
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit_application'
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	 from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:575:in `run'
	 from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:737:in `init_window'
	 from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:200:in `run'
	 from exe/vimamsa:39:in `<main>'
/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/shell.rb:60:in `extend_object': can't modify frozen object: #<GObjectIntrospection::Loader::Invoker:0x00007f78319e6a00> (FrozenError)
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/shell.rb:60:in `extend'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/shell.rb:60:in `add_commands'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/shell.rb:52:in `before_loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/history.rb:25:in `before_loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-multi_line-0.3.1/lib/ripl/multi_line.rb:18:in `before_loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/readline.rb:6:in `before_loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/completion.rb:5:in `before_loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/shell.rb:34:in `loop'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl/runner.rb:49:in `start'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/ripl-0.7.1/lib/ripl.rb:7:in `start'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:711:in `rescue in invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:707:in `invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:575:in `run'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:737:in `init_window'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:200:in `run'
	from exe/vimamsa:39:in `<main>'
/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit': exit (SystemExit)
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit_application'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:575:in `run'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:737:in `init_window'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:200:in `run'
	from exe/vimamsa:39:in `<main>'
/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/glib2-4.2.0/lib/glib2.rb:46:in `exit_application': exit (SystemExit)
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:708:in `invoke'
	from /home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:575:in `run'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:737:in `init_window'
	from /home/samsam/Drive/code/vimamsa/git/lib/vimamsa/gui.rb:200:in `run'
	from exe/vimamsa:39:in `<main>'


```

**Comment by SamiSieranoja** [comment]
This might be some kind of concurrency issue. I can most reliably replicate this if audio playback is happening on the background and then I do some kind of operation using the GTK4 gui (doesn't matter what).

Here are some errors from a crash:

/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke': undefined method `call' for "14:12:58":String

/home/samsam/.rbenv/versions/3.1.3/lib/ruby/gems/3.1.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:705:in `invoke': undefined method `call' for "  pageup page_up\n":String

A workaround might be to separate audio playback to a different process.

**Comment by kou** [comment]
Could you create a minimal reproducible script?

**Comment by SamiSieranoja** [comment]
Here's a script to reproduce the bug:
https://gist.github.com/SamiSieranoja/4f50617886173dfe728cf569ed5389a3

And here's a zip-file containing example audio file (Creative Commons [by-nc-sa]) and screen recording of how the bug occurs:
http://samiddhi.net/files/bug00.zip

**Comment by kou** [comment]
Thanks. I've fixed this.
