### ISSUE TITLE
Unable to load application: GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'Arrow' (any version) not found

### ISSUE THREAD

**Issue by hmfarooq** [ruby-gnome/ruby-gnome#1590]
gem file 

```ruby
source "https://rubygems.org"

ruby "2.7.2"
```

I am deploying this code to Heroku with Buildpack

1. heroku_buildpack/apt
2. ruby

I and using these gems that have this dependency.

```ruby
gem 'red-arrow', '~> 14.0', '>= 14.0.1'
gem 'red-parquet', '~> 14.0', '>= 14.0.1'
```

and having the below errors. I have specified ruby version but it still looking in ruby.2.7.0

```text
Unable to load application: GObjectIntrospection::RepositoryError::TypelibNotFound: Typelib file for namespace 'Arrow' (any version) not found
2023-11-21T13:46:34.717248+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.7.0/bin/puma)
2023-11-21T13:46:34.717421+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:40:in `require': Typelib file for namespace 'Arrow' (any version) not found (GObjectIntrospection::RepositoryError::TypelibNotFound)
2023-11-21T13:46:34.717426+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:40:in `load'
2023-11-21T13:46:34.717427+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:25:in `load'
2023-11-21T13:46:34.717427+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-14.0.1/lib/arrow/loader.rb:24:in `load'
2023-11-21T13:46:34.717428+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-14.0.1/lib/arrow.rb:29:in `<module:Arrow>'
2023-11-21T13:46:34.717428+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/red-arrow-14.0.1/lib/arrow.rb:25:in `<main>'
2023-11-21T13:46:34.717430+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717430+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717432+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
2023-11-21T13:46:34.717432+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
2023-11-21T13:46:34.717432+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/red-parquet-14.0.1/lib/parquet.rb:18:in `<main>'
2023-11-21T13:46:34.717433+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717434+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717434+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
2023-11-21T13:46:34.717434+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:38:in `require'
2023-11-21T13:46:34.717438+00:00 app[web.1]: from /app/app/workers/concat_csv_file_worker.rb:5:in `<main>'
2023-11-21T13:46:34.717439+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717440+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.10.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:28:in `require'
2023-11-21T13:46:34.717440+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/dead_end-3.1.1/lib/dead_end/core_ext.rb:19:in `require'
2023-11-21T13:46:34.717440+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:30:in `require'
2023-11-21T13:46:34.717440+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
2023-11-21T13:46:34.717456+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
2023-11-21T13:46:34.717456+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
2023-11-21T13:46:34.717456+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
2023-11-21T13:46:34.717457+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
2023-11-21T13:46:34.717457+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
2023-11-21T13:46:34.717457+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
2023-11-21T13:46:34.717457+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
2023-11-21T13:46:34.717458+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
2023-11-21T13:46:34.717458+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
2023-11-21T13:46:34.717458+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
2023-11-21T13:46:34.717458+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
2023-11-21T13:46:34.717459+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
2023-11-21T13:46:34.717459+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
2023-11-21T13:46:34.717459+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
2023-11-21T13:46:34.717459+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
2023-11-21T13:46:34.717460+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `instance_exec'
2023-11-21T13:46:34.717460+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `run'
2023-11-21T13:46:34.717461+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
2023-11-21T13:46:34.717461+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
2023-11-21T13:46:34.717462+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2023-11-21T13:46:34.717470+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
2023-11-21T13:46:34.717471+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
2023-11-21T13:46:34.717471+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
2023-11-21T13:46:34.717471+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
2023-11-21T13:46:34.717472+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
2023-11-21T13:46:34.717476+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
2023-11-21T13:46:34.717476+00:00 app[web.1]: from /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
2023-11-21T13:46:34.717477+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:60:in `run_initializers'
2023-11-21T13:46:34.717477+00:00 app[web.1]: from /app/vendor/bundle/ruby/2.7.0/gems/railties-6.1.5.1/lib/rails/application.rb:391:in `initialize!'
2023-11-21T13:46:34.717481+00:00 app[web.1]: from /app/config/environment.rb:23:in `<top (required)>'
2023-11-21T13:46:34.717482+00:00 app[web.1]: from config.ru:6:in `require_relative'
2023-11-21T13:46:34.717483+00:00 app[web.1]: from config.ru:6:in `block in <main>'
```

**Comment by kou** [comment]
Could you add the followings to your `Aptfile`:

```text
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/gir1.2-arrow-1.0_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/gir1.2-parquet-1.0_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow-acero-dev_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow-acero1400_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow-dev_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow-glib-dev_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow-glib1400_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libarrow1400_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libparquet-dev_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libparquet-glib-dev_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libparquet-glib1400_14.0.1-1_amd64.deb
https://apache.jfrog.io/artifactory/arrow/ubuntu/pool/jammy/main/a/apache-arrow/libparquet1400_14.0.1-1_amd64.deb
```

**Comment by kou** [comment]
No response.
