### ISSUE TITLE
how to pass keyword arguments into `Gst::Pad.new`? (beginner's question)

### ISSUE THREAD

**Issue by HuBandiT** [ruby-gnome/ruby-gnome#1592]
Greetings again,

I am having difficulty passing my arguments in as keyword arguments:
```
irb(main):038:0> p = Gst::Pad.new name: "somename", direction: Gst::PadDirection::SRC
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:370:in `initialize': wrong arguments: Gst::Pad#initialize({:name=>"somename", :direction=>#<Gst::PadDirection src>}): (ArgumentError)
available signatures:
Gst::Pad#initialize(name: (may be null) utf8, direction: interface(Gst::PadDirection(GstPadDirection)))
Gst::Pad#initialize(templ: interface(NilClass(void)), name: utf8)
Gst::Pad#initialize(templ: interface(Gst::PadTemplate(GstPadTemplate)), name: (may be null) utf8)
        from (irb):38:in `new'
        from (irb):38:in `<main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from C:/Ruby32-x64/bin/irb:33:in `load'
        from C:/Ruby32-x64/bin/irb:33:in `<main>'
irb(main):039:0> p = Gst::Pad.new(name: "somename", direction: Gst::PadDirection::SRC)
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:370:in `initialize': wrong arguments: Gst::Pad#initialize({:name=>"somename", :direction=>#<Gst::PadDirection src>}): (ArgumentError)
available signatures:
Gst::Pad#initialize(name: (may be null) utf8, direction: interface(Gst::PadDirection(GstPadDirection)))
Gst::Pad#initialize(templ: interface(NilClass(void)), name: utf8)
Gst::Pad#initialize(templ: interface(Gst::PadTemplate(GstPadTemplate)), name: (may be null) utf8)
        from (irb):39:in `new'
        from (irb):39:in `<main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from C:/Ruby32-x64/bin/irb:33:in `load'
        from C:/Ruby32-x64/bin/irb:33:in `<main>'
irb(main):040:0> p = Gst::Pad.new(**{name: "somename", direction: Gst::PadDirection::SRC})
C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:370:in `initialize': wrong arguments: Gst::Pad#initialize({:name=>"somename", :direction=>#<Gst::PadDirection src>}): (ArgumentError)
available signatures:
Gst::Pad#initialize(name: (may be null) utf8, direction: interface(Gst::PadDirection(GstPadDirection)))
Gst::Pad#initialize(templ: interface(NilClass(void)), name: utf8)
Gst::Pad#initialize(templ: interface(Gst::PadTemplate(GstPadTemplate)), name: (may be null) utf8)
        from (irb):40:in `new'
        from (irb):40:in `<main>'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
        from C:/Ruby32-x64/bin/irb:33:in `load'
        from C:/Ruby32-x64/bin/irb:33:in `<main>'
```

What is the correct syntax please? I have double-checked and I do not see my mistake.

Thank you in advance.

**Comment by HuBandiT** [comment]
oh, found it: don't specify the arguments as keywords – simply specify them directly:
```
irb(main):003:0> p = Gst::Pad.new "somename", Gst::PadDirection::SRC
=> #<Gst::Pad:000002188ad9ae28 ptr=0000021889aac8c0>
```

I was confused because GTK4 (very courteously) does offer keyword arguments:
```
irb(main):008:0> b = Gtk::Button.new label: "something"
=> #<Gtk::Button:000002189660bb60 ptr=00000218964612a0>
irb(main):009:0> b.label
=> "something"
```
