### ISSUE TITLE
install fails on M1 with Mac OS Sonoma with ffi.h file not found

### ISSUE THREAD

**Issue by javinto** [ruby-gnome/ruby-gnome#1593]
We cannot get gobject-introspection 4.2.0 installed on a Apple M1-pro with Mac Os Sonoma.

ruby 3.1.3

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 
    current directory: /Users/me/.rvm/gems/ruby-3.1.3/gems/gobject-introspection-4.2.0/ext/gobject-introspection
/Users/me/.rvm/rubies/ruby-3.1.3/bin/ruby -I /Users/me/.rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0 extconf.rb build.cairo-gobject build.gio2
--with-ldflags\=-Wl,-undefined,dynamic_lookup
checking for --enable-debug-build option... no
checking for -Wall option to compiler... yes
checking for -Wcast-align option to compiler... yes
checking for -Wextra option to compiler... no
checking for -Wformat=2 option to compiler... yes
checking for -Winit-self option to compiler... yes
checking for -Wlarger-than-65500 option to compiler... yes
checking for -Wmissing-declarations option to compiler... yes
checking for -Wmissing-format-attribute option to compiler... yes
checking for -Wmissing-include-dirs option to compiler... yes
checking for -Wmissing-noreturn option to compiler... yes
checking for -Wmissing-prototypes option to compiler... yes
checking for -Wnested-externs option to compiler... yes
checking for -Wold-style-definition option to compiler... yes
checking for -Wpacked option to compiler... yes
checking for -Wp,-D_FORTIFY_SOURCE=2 option to compiler... yes
checking for -Wpointer-arith option to compiler... yes
checking for -Wundef option to compiler... yes
checking for -Wout-of-line-declaration option to compiler... yes
checking for -Wunsafe-loop-optimizations option to compiler... no
checking for -Wwrite-strings option to compiler... yes
checking for Homebrew... yes
checking for gobject-introspection-1.0... yes (1.78.1)
creating rbgiversion.h
creating gobject-introspection-enum-types.c
creating gobject-introspection-enum-types.h
creating ruby-gobject-introspection.pc
creating Makefile
 
current directory: /Users/me/.rvm/gems/ruby-3.1.3/gems/gobject-introspection-4.2.0/ext/gobject-introspection
make DESTDIR\= sitearchdir\=./.gem.20231130-42477-33sd5j sitelibdir\=./.gem.20231130-42477-33sd5j clean
 
current directory: /Users/me/.rvm/gems/ruby-3.1.3/gems/gobject-introspection-4.2.0/ext/gobject-introspection
make DESTDIR\= sitearchdir\=./.gem.20231130-42477-33sd5j sitelibdir\=./.gem.20231130-42477-33sd5j
compiling gobject-introspection-enum-types.c
compiling rb-gi-arg-info.c
In file included from rb-gi-arg-info.c:21:
In file included from ./rb-gi-private.h:28:
/opt/homebrew/Cellar/gobject-introspection/1.78.1/include/gobject-introspection-1.0/girffi.h:25:10: fatal error: 'ffi.h' file not found
#include <ffi.h>
         ^~~~~~~
1 error generated.
make: *** [rb-gi-arg-info.o] Error 1
 
make failed, exit code 2
 
Gem files will remain installed in /Users/me/.rvm/gems/ruby-3.1.3/gems/gobject-introspection-4.2.0 for inspection.
Results logged to /Users/me/.rvm/gems/ruby-3.1.3/extensions/arm64-darwin-23/3.1.0/gobject-introspection-4.2.0/gem_make.out
 
  /Users/me/.rvm/rubies/ruby-3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'

```

Is there a way to solve this?

**Comment by kou** [comment]
Does `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi` exist?

Could you also show the output of the following command line?

```bash
ruby -v -r pkg-config -e 'p PKGConfig.cflags("gobject-introspection-1.0")'
```

**Comment by javinto** [comment]
`/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/ffi` does NOT exist. 

However the corresponding MacOSX13.3, MacOSX13, MacOSX14.0 and MacOSX14 folders do exist.

And the other output you requested:
```
ruby -v -r pkg-config -e 'p PKGConfig.cflags("gobject-introspection-1.0")'. :
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- pkg-config (LoadError)
       from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

```

**Comment by javinto** [comment]
Yes! That helped: `brew reinstall pkg-config`

The reason that Ruby 2.6.10 was shown is that this is the OS Ruby version. But we are using RVM with Ruby 3.1.3 installed as sole version. 

Thank you very very much for your cooperation!

Greetings from the Netherlands
