### ISSUE TITLE
gobject-introspection gem 4.2.0 testsuite failure with GLib 2.79.0 (perhaps)

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1604]
gobject-introspection gem 4.2.0 (on Fedora rubygem-goject-introspection rpm) now sees test failure on Fedora 40 like:

```
Started
F
===============================================================================
Failure: test_enumerable(TestRepository)
/builddir/build/BUILD/gobject-introspection-4.2.0/usr/share/gems/gems/gobject-introspection-4.2.0/test/test-repository.rb:57:in `test_enumerable'
     54:     namespaces = @repository.collect do |info|
     55:       info.namespace
     56:     end
  => 57:     assert_equal(["GLib", "GObject", "Gio"].sort, namespaces.uniq.sort)
     58:   end
     59: 
     60:   def test_find_by_gtype
<["GLib", "GObject", "Gio"]> expected but was
<["GLib", "GModule", "GObject", "Gio"]>
diff:
? ["GLib", "GModule", "GObject", "Gio"]
===============================================================================
F
===============================================================================
Failure: test_loaded_namespaces(TestRepository)
/builddir/build/BUILD/gobject-introspection-4.2.0/usr/share/gems/gems/gobject-introspection-4.2.0/test/test-repository.rb:49:in `test_loaded_namespaces'
     46:   end
     47: 
     48:   def test_loaded_namespaces
  => 49:     assert_equal(["GLib", "GObject", "Gio"].sort,
     50:                  @repository.loaded_namespaces.sort)
     51:   end
     52: 
<["GLib", "GObject", "Gio"]> expected but was
<["GLib", "GModule", "GObject", "Gio"]>
diff:
? ["GLib", "GModule", "GObject", "Gio"]
===============================================================================
Finished in 0.053992022 seconds.
-------------------------------------------------------------------------------
136 tests, 136 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
```

I suspect this is due to GLib 2.79.0 change:
https://gitlab.gnome.org/GNOME/glib/-/commit/9c4ff01febffe5365b33844256f74cbdbf3d0345
The above change looks like gio gir now depends on glib, gobject and gmodule.
This change is during GLib 2.79.x period, so this dependency may change again.

**Comment by kou** [comment]
Wow. Thanks for your report.

Could you try https://github.com/ruby-gnome/ruby-gnome/commit/b435e4963a578bd3fb3bb107632bb56338022151 ?
Should we release a new version for Fedora? Or cherry-pick is acceptable for now?

**Comment by mtasaka** [comment]
Okay, I will try later (Today I may not have enough time).

For now cherry-pick is okay. I can backport the commit to Fedora rpm.

**Comment by kou** [comment]
Thanks. No problem.

**Comment by mtasaka** [comment]
Confirmed fixed, thank you!
