### ISSUE TITLE
gio2: undefined method `registered` for class #<Class:Gio::ContentType>

### ISSUE THREAD

**Issue by route** [ruby-gnome/ruby-gnome#1610]
When I open pure irb and call `require 'parquet'`

It throws this error:

```shell
Traceback (most recent call last):
	21: from /Users/route/.rbenv/versions/2.7.8/bin/irb:25:in `<main>'
	20: from /Users/route/.rbenv/versions/2.7.8/bin/irb:25:in `load'
	19: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	 2: from (irb):1:in `<main>'
	 1: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require'
/Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:86:in `require': cannot load such file -- parquet (LoadError)
	... 10 levels...
	16: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/red-arrow-14.0.1/lib/arrow.rb:19:in `<top (required)>'
	15: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'
	14: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'
	13: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2.rb:21:in `<top (required)>'
	12: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2.rb:31:in `<module:Gio>'
	11: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:41:in `load'
	10: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:636:in `prepare_class'
	 9: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gobject-introspection-4.2.0/lib/gobject-introspection/loader.rb:49:in `block in load'
	 8: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/loader.rb:41:in `post_load'
	 7: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/loader.rb:64:in `require_libraries'
	 6: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'
	 5: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:97:in `require'
	 4: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/content-type.rb:17:in `<top (required)>'
	 3: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/content-type.rb:18:in `<module:Gio>'
	 2: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/content-type.rb:19:in `<class:ContentType>'
	 1: from /Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/content-type.rb:20:in `singleton class'
/Users/route/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/gio2-4.2.0/lib/gio2/content-type.rb:20:in `alias_method': undefined method `registered' for class `#<Class:Gio::ContentType>' (NameError)
```

Checked that on 2.7.8 and 3.2.2. Same issue. I think `alias_method :registered_raw, :registered` should be after method.

**Comment by kou** [comment]
Hmm. It seems that this is a Homebrew's GLib problem.

`$(brew --prefix)/share/gir-1.0/Gio-2.0.gir` has the following content. `introspectable="0"` is the important part. It seems that metadata for GObject Introspection isn't used. It should be extracted from https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gcontenttype.c?ref_type=heads#L936-945 .

```xml
    <function name="content_types_get_registered"
              c:identifier="g_content_types_get_registered"
              introspectable="0">
      <source-position filename="gio/gcontenttype.h" line="72"/>
      <return-value>
        <type name="GLib.List" c:type="GList*">
          <type name="gpointer" c:type="gpointer"/>
        </type>
      </return-value>
    </function>
```

Could you report this to Homebrew?

**Comment by tatethurston** [comment]
Encountered the same issue. Opened https://github.com/Homebrew/homebrew-core/issues/167524 to kickstart a conversation.

**Comment by route** [comment]
@tatethurston Thanks!
