### ISSUE TITLE
ruby-gdk_pixbuf 4.2.2 testsuite fails with gdk-pixbuf2 2.42.11 due to unwilling change :(

### ISSUE THREAD

**Issue by mtasaka** [ruby-gnome/ruby-gnome#1614]
As written above, ruby-gdk_pixbuf 4.2.2 testsuite fails with gdk-pixbuf2 2.42.11 as:

```
Loaded suite test
StartedGdkPixbuf-WARNING **: Error loading XPM image loader: Image type “xpm” is not supported
E
===============================================================================
Error: test: xpm(TestPixbuf::.new::Hash form): RuntimeError: failed to initialize	from /usr/share/gems/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:713:in `invoke'
	from /usr/share/gems/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:352:in `initialize_new_from_xpm_data'
	from /builddir/build/BUILD/gdk_pixbuf2-4.2.2/usr/share/gems/gems/gdk_pixbuf2-4.2.2/lib/gdk_pixbuf2/pixbuf.rb:143:in `initialize_with_hash'
	from /builddir/build/BUILD/gdk_pixbuf2-4.2.2/usr/share/gems/gems/gdk_pixbuf2-4.2.2/lib/gdk_pixbuf2/pixbuf.rb:26:in `initialize'
	from /builddir/build/BUILD/gdk_pixbuf2-4.2.2/usr/share/gems/gems/gdk_pixbuf2-4.2.2/lib/gdk_pixbuf2/deprecated.rb:45:in `new'
	from /builddir/build/BUILD/gdk_pixbuf2-4.2.2/usr/share/gems/gems/gdk_pixbuf2-4.2.2/lib/gdk_pixbuf2/deprecated.rb:45:in `new'
	from /builddir/build/BUILD/gdk_pixbuf2-4.2.2/usr/share/gems/gems/gdk_pixbuf2-4.2.2/test/test-pixbuf.rb:140:in `block (3 levels) in <class:TestPixbuf>'

===============================================================================
Finished in 0.098976287 seconds.
-------------------------------------------------------------------------------
30 tests, 53 assertions, 0 failures, 2 errors, 0 pendings, 0 omissions, 0 notifications
93.3333% passed
-------------------------------------------------------------------------------
....
```

This is because  gdk-pixbuf2 2.42.11 stopped supporting xpm format by default (it can be enabled with meson option, but it is disabled by default) :(

https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/commit/e052a112075a19fb75f1f2ff3de4c82923de13f2

**Comment by kou** [comment]
Can we solve this by installing `gdk-pixbuf2-modules` in the test environment like feb5965fdd52c268e51627c561c8fdf007afb927 ?
(Or we can remove the test.)
