### ISSUE TITLE
Unable to install `atk` when installing `gtk3` gem

### ISSUE THREAD

**Issue by RangHo** [ruby-gnome/ruby-gnome#1617]
Hi!

I'm trying to start a new app using bundler, but the native extension for `atk` fails to build.
The logs don't show anything interesting to start debugging, so I'm kinda stuck here.

Here is my terminal output:

```console
$ bundle install
Fetching gem metadata from https://rubygems.org/.....
Resolving dependencies...
Installing atk 4.2.2 with native extensions
Installing gobject-introspection 4.2.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/atk-4.2.2/dependency-check
/home/rangho/.local/share/mise/installs/ruby/3.3.3/bin/ruby -rrubygems /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/exe/rake
RUBYARCHDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2
RUBYLIBDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2

rake failed, exit code 1

Gem files will remain installed in /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/atk-4.2.2 for inspection.
Results logged to /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2/gem_make.out

  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/rake_builder.rb:30:in `build'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/source/rubygems.rb:206:in `install'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in `install'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in `do_install'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/worker.rb:62:in `apply_func'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/worker.rb:54:in `process_queue'
  /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing atk (4.2.2), and Bundler cannot continue.

In Gemfile:
  raw was resolved to 0.1.0, which depends on
    gtk3 was resolved to 4.2.2, which depends on
      atk
```

I checked the log file as well, but nothing useful was found:

```console
$cat /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2/gem_make.out
current directory: /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/atk-4.2.2/dependency-check
/home/rangho/.local/share/mise/installs/ruby/3.3.3/bin/ruby -rrubygems /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/exe/rake RUBYARCHDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2 RUBYLIBDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2

rake failed, exit code 1
```

Running the build command myself yield also nothing super interesting. The command just exits with 1.
Forcing verbose output doesn't show anything at all, and dry-running the command shows the following:

```console
$ /home/rangho/.local/share/mise/installs/ruby/3.3.3/bin/ruby -rrubygems /home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/gems/rake-13.2.1/exe/rake -n RUBYARCHDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2 RUBYLIBDIR\=/home/rangho/.local/share/mise/installs/ruby/3.3.3/lib/ruby/gems/3.3.0/extensions/x86_64-linux/3.3.0/atk-4.2.2
** Invoke default (first_time)
** Execute (dry run) default
```

Any ideas how to fix this issue? I suspect a missing devleopment library, but then other gems build just fine.

Thanks in advance!

**Comment by kou** [comment]
What distribution are you using?
Could you show the output of `pkg-config --modversion atk`

**Comment by RangHo** [comment]
I'm using Void Linux (glibc, x86_64), and the command shows:

```console
$ pkg-config --modversion atk
2.52.0
```

It seems Void Linux `atk-devel` package is installed correctly. I'll do some more digging and report back if I find anything.

**Comment by RangHo** [comment]
I found out that other GTK3 apps don't compile on my machine.
Apparently my installation of `atk-devel` was incomplete, and force reinstall has solved the issue.

Sorry for the inconvenience!

Closing this issue.
