### ISSUE TITLE
gobject-introspection: Warning Invalid constant name, for gtk4

### ISSUE THREAD

**Issue by rubyFeedback** [ruby-gnome/ruby-gnome#1618]
ruby foobar.rb

**foobar.rb** content is simply this file:

example-0.rb

From that URL:

https://github.com/ruby-gnome/ruby-gnome/tree/master/gtk4/sample/getting-started

Warning is given:

    /root/.gem/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:187:
    warning: Invalid constant name '0BSD' - skipped

I am not entirely sure, but I believe that warning was not issued in prior releases of ruby-gtk.

It is probably not important, but I just mention it here, in the event someone finds out whether
it is necessary. The computer system I use is Linux, so I am not sure why 0BSD is queried or
checked.

**Comment by kou** [comment]
Could you show full log?
Could you show your environment?
Could you show your GTK 4 (and related libraries) version?

**Comment by kojix2** [comment]
I saw this error too today, it appears on Ubuntu and also on macOS.

I tried to create a Dockerfile to reproduce the problem, but could not call gtk4 with Docker.

This one works.

```Dockerfile
FROM ruby:latest

RUN apt-get update && \
    apt-get install -y \
    libatk1.0-dev \
    libgtk-4-dev \
    libgtk-3-dev \
    pkg-config \
    build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN gem install gtk3 gtk4

# Add a script that uses gtk4 to trigger the warning
RUN echo 'require "gtk3"' > test_gtk3.rb
RUN echo 'require "gtk4"' > test_gtk4.rb

CMD ["ruby", "test_gtk3.rb"]
```

This one dose not work.

```Dockerfile
FROM ruby:latest

RUN apt-get update && \
    apt-get install -y \
    libatk1.0-dev \
    libgtk-4-dev \
    libgtk-3-dev \
    pkg-config \
    build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN gem install gtk3 gtk4

# Add a script that uses gtk4 to trigger the warning
RUN echo 'require "gtk3"' > test_gtk3.rb
RUN echo 'require "gtk4"' > test_gtk4.rb

CMD ["ruby", "test_gtk4.rb"] # Change only here
```


```
/usr/local/bundle/gems/gtk4-4.2.2/lib/gtk4/loader.rb:35:in `call_init_function': failed to initialize GTK (Gtk::InitError)
	from /usr/local/bundle/gems/gtk4-4.2.2/lib/gtk4/loader.rb:26:in `pre_load'
	from /usr/local/bundle/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:42:in `block in load'
	from /usr/local/bundle/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:644:in `prepare_class'
	from /usr/local/bundle/gems/gobject-introspection-4.2.2/lib/gobject-introspection/loader.rb:41:in `load'
	from /usr/local/bundle/gems/gtk4-4.2.2/lib/gtk4/loader.rb:21:in `load'
	from /usr/local/bundle/gems/gtk4-4.2.2/lib/gtk4.rb:32:in `<module:Gtk>'
	from /usr/local/bundle/gems/gtk4-4.2.2/lib/gtk4.rb:21:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:141:in `rescue in require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:135:in `require'
	from test_gtk.rb:1:in `<main>'
<internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- gtk4 (LoadError)
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
	from test_gtk.rb:1:in `<main>'
```

**Comment by kou** [comment]
What is your Ubuntu version? 24.04?

**Comment by kou** [comment]
I could reproduce this with GTK 4.14.
I've fixed this. Thanks.
