### ISSUE TITLE
i can't run programs with gtk3

### ISSUE THREAD

**Issue by SenninSensei** [ruby-gnome/ruby-gnome#258]
hello sorry for my bad english.
i download the ruby-gnome2-2.2.1 and do

``` text
ruby extconf.rb
make
sudo make install
```

and now i get an error when i try to require 'gtk3'
i unistall rvm and install again and the gems but still i get the same error i can use gtk2 but gt3 don't

here is the error:

``` text
/home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cairo-gobject (LoadError)
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/sennin/.rvm/gems/ruby-2.1.3/gems/gdk3-2.2.2/lib/gdk3.rb:18:in `<top (required)>'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/sennin/.rvm/gems/ruby-2.1.3/gems/gtk3-2.2.2/lib/gtk3/base.rb:8:in `<top (required)>'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/sennin/.rvm/gems/ruby-2.1.3/gems/gtk3-2.2.2/lib/gtk3.rb:7:in `<top (required)>'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /home/sennin/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from main.rb:11:in `<main>'
```

**Comment by jjgh** [comment]
On Windows: 

```
> ruby -v

Ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32] 

> gem install gtk3

Fetching: pkg-config-1.2.0.gem (100%)
Successfully installed pkg-config-1.2.0
Fetching: native-package-installer-1.0.0.gem (100%)
Successfully installed native-package-installer-1.0.0
Fetching: cairo-1.15.6-x64-mingw32.gem (100%)
Successfully installed cairo-1.15.6-x64-mingw32
Fetching: glib2-3.1.3-x64-mingw32.gem (100%)
Successfully installed glib2-3.1.3-x64-mingw32
Fetching: gobject-introspection-3.1.3-x64-mingw32.gem (100%)
Successfully installed gobject-introspection-3.1.3-x64-mingw32
Fetching: gio2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gio2-3.1.3-x64-mingw32
Fetching: atk-3.1.3-x64-mingw32.gem (100%)
Successfully installed atk-3.1.3-x64-mingw32
Fetching: cairo-gobject-3.1.3-x64-mingw32.gem (100%)
Successfully installed cairo-gobject-3.1.3-x64-mingw32
Fetching: pango-3.1.3-x64-mingw32.gem (100%)
Successfully installed pango-3.1.3-x64-mingw32
Fetching: gdk_pixbuf2-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk_pixbuf2-3.1.3-x64-mingw32
Fetching: gdk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gdk3-3.1.3-x64-mingw32
Fetching: rsvg2-3.1.3-x64-mingw32.gem (100%)
Successfully installed rsvg2-3.1.3-x64-mingw32
Fetching: gtk3-3.1.3-x64-mingw32.gem (100%)
Successfully installed gtk3-3.1.3-x64-mingw32
13 gems installed

> ruby ruby-gnome-example.rb

C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- cairo.so (LoadError)
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:48:in `rescue in <top (required)>'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cairo-1.15.6-x64-mingw32/lib/cairo.rb:44:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/glib2-3.1.3-x64-mingw32/lib/glib2.rb:112:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gobject-introspection-3.1.3-x64-mingw32/lib/gobject-introspection.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Dev/ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gtk3-3.1.3-x64-mingw32/lib/gtk3.rb:17:in `<top (required)>'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/dev/ruby/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from ruby-gnome-example.rb:1:in `<main>'
```
