### ISSUE TITLE
video-sink.rb clutter-gst sample doesn't work

### ISSUE THREAD

**Issue by cedlemo** [ruby-gnome/ruby-gnome#555]
here is the error message:

```
ruby video-sink.rb                                                                                                                             [19:09:20] 
video-sink.rb: line 44
   GLib-GObject-WARNING **:g_object_set_property: construct property "disable-slicing" for object 'ClutterTexture' can't be set after construction
/home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.4/lib/gobject-introspection/loader.rb:384:in `find_suitable_callable_info': wrong number of arguments (1 for 0) (ArgumentError)
    from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.4/lib/gobject-introspection/loader.rb:319:in `block in load_constructor_infos'
    from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.4/lib/gobject-introspection/loader.rb:322:in `call'
    from /home/cedlemo/.gem/ruby/2.2.0/gems/gobject-introspection-3.0.4/lib/gobject-introspection/loader.rb:322:in `block in load_constructor_infos'
    from video-sink.rb:71:in `new'
    from video-sink.rb:71:in `<main>'

```

And the installed gems:

```
atk (3.0.4)
cairo-gobject (3.0.4)
clutter (3.0.4)
clutter-gstreamer (3.0.4)
gdk3 (3.0.4)
gdk_pixbuf2 (3.0.4)
gio2 (3.0.4)
glib2 (3.0.4)
gobject-introspection (3.0.4)
gstreamer (3.0.4)
gtk3 (3.0.4)
pango (3.0.4)
vte3 (3.0.4)

```

**Comment by kou** [comment]
Because the sample requires Clutter Gst 2.0 but you have Clutter Gst 3.0.

We should provide samples for Clutter Gst 3.0.

**Comment by cedlemo** [comment]
I let this issue open and the #554 as well while they are not updated.

**Comment by kou** [comment]
It's reasonable.

**Comment by cedlemo** [comment]
@kou

I have to update gtk-demo as well, I would like to know on which (gstreamer or gtk-demo) on should work first?

**Comment by kou** [comment]
gtk-demo!
Because gtk3 has more users than clutter-gst.

**Comment by cedlemo** [comment]
ok

**Comment by kou** [comment]
We don't do this because Clutter is retired: https://blogs.gnome.org/clutter/2022/02/16/retiring-clutter/
